-- Script para inserir todos os suplementos do JSON na tabela supplements
-- Este script insere os 59 produtos da Atlântica Natural

-- Primeiro, limpar a tabela se necessário (opcional)
-- DELETE FROM public.supplements;

-- Inserir todos os suplementos
INSERT INTO public.supplements (
    id,
    name, 
    active_ingredients, 
    recommended_dosage,
    benefits,
    contraindications,
    category,
    brand,
    is_approved,
    image_url,
    original_price,
    discount_price,
    description,
    stock_quantity,
    tags
) VALUES 
-- CART CONTROL
('CART_CONTROL', 'CART CONTROL', 
 ARRAY['Cafeína', 'Chá Verde', 'L-Carnitina', 'Cromo', 'Capsaicina'],
 '2 cápsulas 30 minutos antes do almoço',
 ARRAY['Acelera metabolismo', 'Reduz gordura abdominal', 'Controla apetite', 'Aumenta termogênese'],
 ARRAY['Hipertensão grave não controlada', 'Gravidez', 'Lactação', 'Problemas cardíacos'],
 'emagrecimento', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/4F46E5/FFFFFF?text=CART+CONTROL',
 189.90, 94.90,
 'Complexo termogênico avançado para controle de peso e aceleração metabólica.',
 150, ARRAY['termogenico', 'emagrecimento', 'metabolismo', 'gordura_abdominal']),

-- A-Z COMPLEX
('AZ_COMPLEX', 'A-Z COMPLEX',
 ARRAY['24 Vitaminas e Minerais', 'Vitamina A', 'Complexo B', 'Vitamina C', 'Vitamina D3', 'Vitamina E', 'Zinco', 'Selênio', 'Magnésio'],
 '1 cápsula ao dia com refeição principal',
 ARRAY['Suporte nutricional completo', 'Aumenta energia', 'Fortalece imunidade', 'Melhora concentração'],
 ARRAY['Hipervitaminose', 'Alergia a algum componente'],
 'vitaminas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/10B981/FFFFFF?text=A-Z+COMPLEX',
 159.90, 79.90,
 'Multivitamínico completo com 24 nutrientes essenciais em doses ideais.',
 200, ARRAY['multivitaminico', 'essencial', 'energia', 'imunidade']),

-- OMEGA 3
('OMEGA_3', 'OMEGA 3',
 ARRAY['EPA 500mg', 'DHA 250mg', 'Vitamina E'],
 '2 cápsulas ao dia com refeições',
 ARRAY['Saúde cardiovascular', 'Reduz triglicerídeos', 'Anti-inflamatório', 'Melhora cognição'],
 ARRAY['Alergia a peixes', 'Uso de anticoagulantes (consultar médico)'],
 'cardiovascular', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/F59E0B/FFFFFF?text=OMEGA+3',
 149.90, 74.90,
 'Ômega 3 de alta concentração (EPA + DHA) purificado por destilação molecular.',
 180, ARRAY['omega3', 'cardiovascular', 'antiinflamatorio', 'cerebro']),

-- CLORETO DE MAGNÉSIO
('CLORETO_MAGNESIO', 'CLORETO DE MAGNÉSIO',
 ARRAY['Cloreto de Magnésio P.A. 500mg'],
 '1 cápsula 2x ao dia (manhã e noite)',
 ARRAY['Regula pressão arterial', 'Melhora sono', 'Relaxa músculos', 'Reduz cãibras'],
 ARRAY['Insuficiência renal', 'Bloqueio cardíaco'],
 'minerais', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/8B5CF6/FFFFFF?text=CLORETO+DE+MAGNÉSIO',
 89.90, 44.90,
 'Magnésio P.A. de alta biodisponibilidade para saúde cardiovascular e muscular.',
 250, ARRAY['magnesio', 'sono', 'pressao', 'cãibras']),

-- MACA PERUANA
('MACA_PERUANA', 'MACA PERUANA',
 ARRAY['Extrato de Maca Peruana 500mg', 'Padronizado em macamidas'],
 '2 cápsulas ao dia (manhã)',
 ARRAY['Aumenta energia', 'Melhora libido', 'Equilíbrio hormonal', 'Combate fadiga'],
 ARRAY['Gravidez', 'Lactação', 'Problemas tireoidianos não controlados'],
 'energia', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/F59E0B/FFFFFF?text=MACA+PERUANA',
 139.90, 69.90,
 'Maca Peruana premium dos Andes, padronizada em macamidas para máxima eficácia.',
 120, ARRAY['energia', 'libido', 'hormonal', 'fadiga']),

-- VITAMINA D3
('VITAMINA_D3', 'VITAMINA D3 2000UI',
 ARRAY['Colecalciferol (D3) 2000UI'],
 '1 cápsula ao dia com refeição',
 ARRAY['Fortalece ossos', 'Melhora imunidade', 'Previne osteoporose', 'Melhora humor'],
 ARRAY['Hipercalcemia', 'Sarcoidose'],
 'vitaminas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/10B981/FFFFFF?text=VITAMINA+D3',
 79.90, 39.90,
 'Vitamina D3 na forma ativa com máxima biodisponibilidade.',
 300, ARRAY['vitamina_d', 'ossos', 'imunidade', 'essencial']),

-- VITAMINA B12
('VITAMINA_B12', 'VITAMINA B12 METILCOBALAMINA',
 ARRAY['Metilcobalamina 1000mcg'],
 '1 cápsula ao dia',
 ARRAY['Combate fadiga', 'Melhora memória', 'Protege nervos', 'Essencial para vegetarianos'],
 ARRAY['Alergia a cobalamina'],
 'vitaminas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/EF4444/FFFFFF?text=VITAMINA+B12',
 89.90, 44.90,
 'B12 na forma metilada, mais biodisponível e ativa.',
 200, ARRAY['b12', 'energia', 'memoria', 'vegetarianos']),

-- COLÁGENO
('COLAGENO', 'COLÁGENO HIDROLISADO TIPO II',
 ARRAY['Colágeno Hidrolisado Tipo II 10g', 'Vitamina C 45mg'],
 '1 scoop ao dia dissolvido em água',
 ARRAY['Melhora pele', 'Reduz dor articular', 'Fortalece cabelo e unhas', 'Previne rugas'],
 ARRAY['Alergia a proteínas bovinas ou suínas'],
 'colageno', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/F59E0B/FFFFFF?text=COLÁGENO',
 119.90, 59.90,
 'Colágeno hidrolisado de baixo peso molecular para máxima absorção.',
 180, ARRAY['colageno', 'pele', 'articulacoes', 'beleza']),

-- PROBIÓTICOS
('PROBIOTICOS', 'PROBIÓTICOS 10 BILHÕES UFC',
 ARRAY['10 bilhões UFC', 'Lactobacillus', 'Bifidobacterium', 'FOS (prebiótico)'],
 '1 cápsula ao dia em jejum',
 ARRAY['Regula intestino', 'Fortalece imunidade', 'Reduz gases', 'Melhora digestão'],
 ARRAY['Imunocomprometidos (consultar médico)'],
 'digestao', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/8B5CF6/FFFFFF?text=PROBIÓTICOS',
 109.90, 54.90,
 'Complexo probiótico com 10 cepas selecionadas + prebióticos.',
 150, ARRAY['probioticos', 'intestino', 'imunidade', 'digestao']),

-- CREATINA
('CREATINA', 'CREATINA MONOHIDRATADA PURA',
 ARRAY['Creatina Monohidratada 3g'],
 '1 scoop (3g) ao dia, qualquer horário',
 ARRAY['Aumenta força', 'Ganha massa muscular', 'Melhora performance', 'Acelera recuperação'],
 ARRAY['Problemas renais'],
 'performance', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/10B981/FFFFFF?text=CREATINA',
 129.90, 64.90,
 'Creatina 100% pura, micronizada, sem aditivos.',
 200, ARRAY['creatina', 'forca', 'massa_muscular', 'treino']),

-- WHEY PROTEIN
('WHEY_PROTEIN', 'WHEY PROTEIN CONCENTRADO 80%',
 ARRAY['Whey Protein Concentrado 25g', 'BCAAs 5.5g'],
 '1 scoop (30g) pós-treino ou entre refeições',
 ARRAY['Ganho muscular', 'Recuperação', 'Saciedade', 'Aminoácidos essenciais'],
 ARRAY['Alergia ao leite', 'Intolerância à lactose severa'],
 'proteinas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/EF4444/FFFFFF?text=WHEY+PROTEIN',
 179.90, 89.90,
 'Whey protein de alto valor biológico com 80% de proteína.',
 150, ARRAY['whey', 'proteina', 'massa_muscular', 'recuperacao']),

-- ZINCO
('ZINCO', 'ZINCO QUELADO 30mg',
 ARRAY['Zinco Quelado 30mg'],
 '1 cápsula ao dia com refeição',
 ARRAY['Fortalece imunidade', 'Melhora pele', 'Acelera cicatrização', 'Saúde da tireoide'],
 ARRAY['Uso prolongado acima de 40mg/dia'],
 'minerais', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/8B5CF6/FFFFFF?text=ZINCO',
 79.90, 39.90,
 'Zinco quelado de alta absorção para imunidade e saúde celular.',
 220, ARRAY['zinco', 'imunidade', 'pele', 'cicatrizacao']),

-- VITAMINA C
('VITAMINA_C', 'VITAMINA C 1000mg',
 ARRAY['Ácido Ascórbico 1000mg'],
 '1 cápsula ao dia',
 ARRAY['Antioxidante', 'Imunidade', 'Produção de colágeno', 'Absorção de ferro'],
 ARRAY['Cálculos renais de oxalato'],
 'vitaminas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/EF4444/FFFFFF?text=VITAMINA+C',
 69.90, 34.90,
 'Vitamina C pura de alta potência para imunidade e antioxidação.',
 250, ARRAY['vitamina_c', 'antioxidante', 'imunidade', 'colageno']),

-- SELÊNIO
('SELENIO', 'SELÊNIO 200mcg',
 ARRAY['Selenometionina 200mcg'],
 '1 cápsula ao dia',
 ARRAY['Saúde da tireoide', 'Antioxidante', 'Imunidade', 'Proteção celular'],
 ARRAY['Selenose (intoxicação por selênio)'],
 'minerais', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/F59E0B/FFFFFF?text=SELÊNIO',
 79.90, 39.90,
 'Selênio orgânico de alta biodisponibilidade para tireoide e imunidade.',
 180, ARRAY['selenio', 'tireoide', 'antioxidante', 'imunidade']),

-- ASHWAGANDHA
('ASHWAGANDHA', 'ASHWAGANDHA 500mg',
 ARRAY['Extrato de Ashwagandha 500mg', 'Padronizado 5% withanolidas'],
 '1 cápsula 2x ao dia',
 ARRAY['Reduz estresse', 'Equilibra cortisol', 'Melhora sono', 'Aumenta energia'],
 ARRAY['Gravidez', 'Lactação', 'Hipertireoidismo'],
 'adaptogenos', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/10B981/FFFFFF?text=ASHWAGANDHA',
 139.90, 69.90,
 'Ashwagandha premium padronizada, adaptógeno milenar ayurvédico.',
 130, ARRAY['ashwagandha', 'estresse', 'adaptogeno', 'cortisol']),

-- MELATONINA
('MELATONINA', 'MELATONINA 3mg',
 ARRAY['Melatonina 3mg'],
 '1 cápsula 30 minutos antes de dormir',
 ARRAY['Melhora sono', 'Regula ciclo circadiano', 'Reduz jet lag', 'Antioxidante'],
 ARRAY['Gravidez', 'Lactação', 'Doenças autoimunes'],
 'sono', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/8B5CF6/FFFFFF?text=MELATONINA',
 69.90, 34.90,
 'Melatonina pura para regularização do ciclo do sono.',
 280, ARRAY['melatonina', 'sono', 'insonia', 'circadiano']),

-- L-GLUTAMINA
('GLUTAMINA', 'L-GLUTAMINA 5g',
 ARRAY['L-Glutamina 5g'],
 '1 scoop (5g) pós-treino ou antes de dormir',
 ARRAY['Saúde intestinal', 'Recuperação muscular', 'Imunidade', 'Anti-catabolismo'],
 ARRAY['Problemas hepáticos graves'],
 'aminoacidos', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/EF4444/FFFFFF?text=L-GLUTAMINA',
 119.90, 59.90,
 'L-Glutamina pura para intestino e recuperação muscular.',
 140, ARRAY['glutamina', 'intestino', 'recuperacao', 'imunidade']),

-- BCAA
('BCAA', 'BCAA 2:1:1 5g',
 ARRAY['L-Leucina 2.5g', 'L-Isoleucina 1.25g', 'L-Valina 1.25g'],
 '1 scoop durante ou pós-treino',
 ARRAY['Reduz fadiga', 'Recuperação muscular', 'Preserva massa', 'Performance'],
 ARRAY['ELA (Esclerose Lateral Amiotrófica)'],
 'aminoacidos', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/F59E0B/FFFFFF?text=BCAA',
 129.90, 64.90,
 'BCAAs na proporção ideal 2:1:1 para máxima eficácia.',
 160, ARRAY['bcaa', 'aminoacidos', 'fadiga', 'treino']),

-- COENZIMA Q10
('COENZIMA_Q10', 'COENZIMA Q10 100mg',
 ARRAY['Ubiquinona (CoQ10) 100mg'],
 '1 cápsula ao dia com refeição gordurosa',
 ARRAY['Energia celular', 'Saúde cardíaca', 'Antioxidante', 'Anti-envelhecimento'],
 ARRAY['Uso de varfarina (consultar médico)'],
 'energia', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/10B981/FFFFFF?text=COENZIMA+Q10',
 159.90, 79.90,
 'Coenzima Q10 de alta pureza para produção de energia mitocondrial.',
 100, ARRAY['coq10', 'energia', 'cardiovascular', 'mitocondria']),

-- CÚRCUMA
('CURCUMA', 'CÚRCUMA + PIPERINA 500mg',
 ARRAY['Extrato de Cúrcuma 450mg (95% curcuminoides)', 'Piperina 5mg'],
 '1 cápsula 2x ao dia com refeições',
 ARRAY['Anti-inflamatório', 'Reduz dor articular', 'Antioxidante', 'Saúde digestiva'],
 ARRAY['Obstrução das vias biliares', 'Gravidez'],
 'antiinflamatorios', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/8B5CF6/FFFFFF?text=CÚRCUMA',
 129.90, 64.90,
 'Curcumina padronizada 95% com piperina para máxima absorção.',
 150, ARRAY['curcuma', 'antiinflamatorio', 'dor', 'antioxidante']),

-- SPIRULINA
('SPIRULINA', 'SPIRULINA 500mg',
 ARRAY['Spirulina platensis 500mg'],
 '2 cápsulas 2x ao dia',
 ARRAY['Proteína completa', 'Antioxidante', 'Energia', 'Desintoxicação'],
 ARRAY['Fenilcetonúria', 'Doenças autoimunes'],
 'superalimentos', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/EF4444/FFFFFF?text=SPIRULINA',
 99.90, 49.90,
 'Spirulina orgânica, superalimento rico em proteínas e nutrientes.',
 170, ARRAY['spirulina', 'superalimento', 'proteina', 'energia']),

-- FERRO
('FERRO', 'FERRO QUELADO 14mg',
 ARRAY['Ferro Bisglicinato 14mg', 'Vitamina C 45mg'],
 '1 cápsula ao dia em jejum',
 ARRAY['Combate anemia', 'Aumenta energia', 'Melhora concentração', 'Sem desconforto gástrico'],
 ARRAY['Hemocromatose', 'Hemossiderose'],
 'minerais', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/F59E0B/FFFFFF?text=FERRO',
 89.90, 44.90,
 'Ferro quelado de alta absorção sem desconforto gastrointestinal.',
 200, ARRAY['ferro', 'anemia', 'energia', 'concentracao']),

-- CÁLCIO + K2
('CALCIO_VITAMINA_K2', 'CÁLCIO + VITAMINA D3 + K2',
 ARRAY['Cálcio 600mg', 'Vitamina D3 400UI', 'Vitamina K2 (MK-7) 45mcg'],
 '1 cápsula 2x ao dia com refeições',
 ARRAY['Fortalece ossos', 'Previne osteoporose', 'Saúde cardiovascular', 'Absorção ideal'],
 ARRAY['Hipercalcemia', 'Uso de anticoagulantes'],
 'ossos', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/10B981/FFFFFF?text=CÁLCIO+K2',
 139.90, 69.90,
 'Trio sinérgico para saúde óssea e cardiovascular máxima.',
 130, ARRAY['calcio', 'ossos', 'vitamina_k2', 'osteoporose']),

-- L-TEANINA
('L_TEANINA', 'L-TEANINA 200mg',
 ARRAY['L-Teanina 200mg'],
 '1 cápsula ao dia, manhã ou tarde',
 ARRAY['Foco sem nervosismo', 'Relaxamento', 'Reduz ansiedade', 'Melhora sono'],
 ARRAY['Pressão baixa'],
 'foco', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/8B5CF6/FFFFFF?text=L-TEANINA',
 119.90, 59.90,
 'L-Teanina pura para foco relaxado e bem-estar mental.',
 110, ARRAY['teanina', 'foco', 'relaxamento', 'ansiedade']),

-- TRIBULUS
('TRIBULUS_TERRESTRIS', 'TRIBULUS TERRESTRIS 500mg',
 ARRAY['Extrato de Tribulus 500mg', 'Padronizado 40% saponinas'],
 '1 cápsula 2x ao dia',
 ARRAY['Melhora libido', 'Aumenta energia', 'Vitalidade', 'Performance física'],
 ARRAY['Câncer de próstata', 'Gravidez', 'Lactação'],
 'libido', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/EF4444/FFFFFF?text=TRIBULUS',
 129.90, 64.90,
 'Tribulus padronizado para vitalidade e energia masculina.',
 120, ARRAY['tribulus', 'libido', 'vitalidade', 'energia']),

-- VITAMINA E
('VITAMINA_E', 'VITAMINA E 400UI',
 ARRAY['D-alfa-tocoferol 400UI'],
 '1 cápsula ao dia com refeição',
 ARRAY['Antioxidante potente', 'Protege células', 'Saúde da pele', 'Cardiovascular'],
 ARRAY['Uso de anticoagulantes'],
 'vitaminas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/F59E0B/FFFFFF?text=VITAMINA+E',
 89.90, 44.90,
 'Vitamina E natural de alta potência para proteção celular.',
 190, ARRAY['vitamina_e', 'antioxidante', 'pele', 'cardiovascular']),

-- BIOTINA
('BIOTINA', 'BIOTINA 10.000mcg',
 ARRAY['Biotina (B7) 10.000mcg'],
 '1 cápsula ao dia',
 ARRAY['Fortalece cabelo', 'Unhas saudáveis', 'Pele radiante', 'Metabolismo energético'],
 ARRAY['Pode interferir em exames laboratoriais'],
 'vitaminas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/10B981/FFFFFF?text=BIOTINA',
 99.90, 49.90,
 'Biotina de alta potência para beleza de cabelo, pele e unhas.',
 210, ARRAY['biotina', 'cabelo', 'unhas', 'pele']),

-- ÁCIDO FÓLICO
('ACIDO_FOLICO', 'ÁCIDO FÓLICO 400mcg',
 ARRAY['Ácido Fólico (B9) 400mcg'],
 '1 cápsula ao dia',
 ARRAY['Essencial na gravidez', 'Produção de células', 'Saúde cardiovascular', 'Previne anemia'],
 ARRAY['Anemia perniciosa não tratada'],
 'vitaminas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/8B5CF6/FFFFFF?text=ÁCIDO+FÓLICO',
 69.90, 34.90,
 'Ácido fólico essencial para gestantes e saúde celular.',
 240, ARRAY['acido_folico', 'gravidez', 'anemia', 'cardiovascular']),

-- VITAMINA A
('VITAMINA_A', 'VITAMINA A 10.000UI',
 ARRAY['Retinol (Vitamina A) 10.000UI'],
 '1 cápsula ao dia com refeição gordurosa',
 ARRAY['Saúde ocular', 'Imunidade', 'Pele saudável', 'Antioxidante'],
 ARRAY['Gravidez (doses altas)', 'Hipervitaminose A'],
 'vitaminas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/EF4444/FFFFFF?text=VITAMINA+A',
 79.90, 39.90,
 'Vitamina A de alta potência para visão e imunidade.',
 160, ARRAY['vitamina_a', 'visao', 'imunidade', 'pele']),

-- NIACINA
('NIACINA', 'NIACINA (B3) 500mg',
 ARRAY['Niacina (B3) 500mg'],
 '1 cápsula ao dia com refeição',
 ARRAY['Metabolismo energético', 'Saúde cardiovascular', 'Colesterol saudável', 'Circulação'],
 ARRAY['Úlcera péptica', 'Gota', 'Doenças hepáticas'],
 'vitaminas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/F59E0B/FFFFFF?text=NIACINA',
 89.90, 44.90,
 'Niacina para energia, metabolismo e saúde cardiovascular.',
 140, ARRAY['niacina', 'b3', 'energia', 'cardiovascular']),

-- VITAMINA B6
('VITAMINA_B6', 'VITAMINA B6 100mg',
 ARRAY['Piridoxina (B6) 100mg'],
 '1 cápsula ao dia',
 ARRAY['Humor e bem-estar', 'Metabolismo de proteínas', 'Sistema nervoso', 'Síntese de neurotransmissores'],
 ARRAY['Neuropatia periférica (doses muito altas)'],
 'vitaminas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/10B981/FFFFFF?text=VITAMINA+B6',
 79.90, 39.90,
 'Vitamina B6 para saúde mental e metabolismo proteico.',
 180, ARRAY['b6', 'humor', 'nervoso', 'proteinas']),

-- VITAMINA B5
('PANTOTENATO', 'ÁCIDO PANTOTÊNICO (B5) 500mg',
 ARRAY['Ácido Pantotênico (B5) 500mg'],
 '1 cápsula ao dia',
 ARRAY['Produção de energia', 'Saúde das glândulas adrenais', 'Síntese de hormônios', 'Metabolismo'],
 ARRAY['Hemofilia'],
 'vitaminas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/8B5CF6/FFFFFF?text=VITAMINA+B5',
 89.90, 44.90,
 'Vitamina B5 para energia e função adrenal.',
 150, ARRAY['b5', 'energia', 'adrenal', 'hormônios']),

-- TIAMINA
('TIAMINA', 'TIAMINA (B1) 100mg',
 ARRAY['Tiamina (B1) 100mg'],
 '1 cápsula ao dia',
 ARRAY['Metabolismo energético', 'Sistema nervoso', 'Função cardíaca', 'Cognição'],
 ARRAY['Alergia a tiamina'],
 'vitaminas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/EF4444/FFFFFF?text=TIAMINA',
 69.90, 34.90,
 'Vitamina B1 para energia e função nervosa.',
 170, ARRAY['b1', 'energia', 'nervoso', 'coração']),

-- RIBOFLAVINA
('RIBOFLAVINA', 'RIBOFLAVINA (B2) 100mg',
 ARRAY['Riboflavina (B2) 100mg'],
 '1 cápsula ao dia',
 ARRAY['Produção de energia', 'Saúde ocular', 'Antioxidante', 'Metabolismo'],
 ARRAY['Fotossensibilidade'],
 'vitaminas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/F59E0B/FFFFFF?text=RIBOFLAVINA',
 69.90, 34.90,
 'Vitamina B2 para energia e proteção celular.',
 160, ARRAY['b2', 'energia', 'visao', 'antioxidante']),

-- INOSITOL
('INOSITOL', 'INOSITOL 500mg',
 ARRAY['Mio-Inositol 500mg'],
 '1 cápsula 2x ao dia',
 ARRAY['Saúde mental', 'Equilíbrio hormonal', 'Sensibilidade à insulina', 'SOP'],
 ARRAY['Transtorno bipolar (doses altas)'],
 'vitaminas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/10B981/FFFFFF?text=INOSITOL',
 119.90, 59.90,
 'Inositol para saúde mental, hormonal e metabólica.',
 130, ARRAY['inositol', 'hormonal', 'insulina', 'ansiedade']),

-- COLINA
('COLINA', 'COLINA 500mg',
 ARRAY['Bitartrato de Colina 500mg'],
 '1 cápsula ao dia',
 ARRAY['Função hepática', 'Memória', 'Metabolismo de gorduras', 'Neurotransmissores'],
 ARRAY['Doenças hepáticas graves'],
 'vitaminas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/8B5CF6/FFFFFF?text=COLINA',
 99.90, 49.90,
 'Colina para saúde do fígado, cérebro e metabolismo.',
 140, ARRAY['colina', 'figado', 'memoria', 'metabolismo']),

-- COBRE
('COBRE', 'COBRE 2mg',
 ARRAY['Cobre Quelado 2mg'],
 '1 cápsula ao dia',
 ARRAY['Formação de glóbulos vermelhos', 'Saúde óssea', 'Função nervosa', 'Antioxidante'],
 ARRAY['Doença de Wilson'],
 'minerais', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/EF4444/FFFFFF?text=COBRE',
 79.90, 39.90,
 'Cobre quelado para produção de energia e antioxidação.',
 150, ARRAY['cobre', 'anemia', 'ossos', 'energia']),

-- MANGANÊS
('MANGANES', 'MANGANÊS 5mg',
 ARRAY['Manganês Quelado 5mg'],
 '1 cápsula ao dia',
 ARRAY['Saúde óssea', 'Metabolismo', 'Antioxidante', 'Produção de colágeno'],
 ARRAY['Doenças hepáticas'],
 'minerais', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/F59E0B/FFFFFF?text=MANGANÊS',
 79.90, 39.90,
 'Manganês para ossos, metabolismo e proteção antioxidante.',
 140, ARRAY['manganes', 'ossos', 'antioxidante', 'metabolismo']),

-- CROMO
('CROMO', 'CROMO PICOLINATO 200mcg',
 ARRAY['Cromo Picolinato 200mcg'],
 '1 cápsula ao dia com refeição',
 ARRAY['Controle glicêmico', 'Reduz compulsão por doces', 'Metabolismo de carboidratos', 'Sensibilidade à insulina'],
 ARRAY['Diabetes descontrolado (consultar médico)'],
 'minerais', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/10B981/FFFFFF?text=CROMO',
 89.90, 44.90,
 'Cromo picolinato para controle de açúcar e apetite.',
 170, ARRAY['cromo', 'diabetes', 'compulsao', 'insulina']),

-- MOLIBDÊNIO
('MOLIBDENIO', 'MOLIBDÊNIO 150mcg',
 ARRAY['Molibdênio Quelado 150mcg'],
 '1 cápsula ao dia',
 ARRAY['Desintoxicação', 'Metabolismo de aminoácidos', 'Produção de ácido úrico', 'Função enzimática'],
 ARRAY['Gota (doses altas)'],
 'minerais', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/8B5CF6/FFFFFF?text=MOLIBDÊNIO',
 79.90, 39.90,
 'Molibdênio para desintoxicação e função enzimática.',
 120, ARRAY['molibdenio', 'desintoxicacao', 'metabolismo', 'enzimas']),

-- IODO
('IODO', 'IODO 150mcg',
 ARRAY['Iodeto de Potássio 150mcg'],
 '1 cápsula ao dia',
 ARRAY['Função tireoidiana', 'Metabolismo', 'Desenvolvimento cognitivo', 'Energia'],
 ARRAY['Hipertireoidismo', 'Tireoidite autoimune'],
 'minerais', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/EF4444/FFFFFF?text=IODO',
 79.90, 39.90,
 'Iodo essencial para tireoide e metabolismo.',
 160, ARRAY['iodo', 'tireoide', 'metabolismo', 'energia']),

-- VANÁDIO
('VANADIO', 'VANÁDIO 50mcg',
 ARRAY['Vanadil Sulfato 50mcg'],
 '1 cápsula ao dia',
 ARRAY['Sensibilidade à insulina', 'Metabolismo de glicose', 'Saúde óssea', 'Performance atlética'],
 ARRAY['Diabetes descontrolado'],
 'minerais', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/F59E0B/FFFFFF?text=VANÁDIO',
 89.90, 44.90,
 'Vanádio para controle glicêmico e sensibilidade à insulina.',
 100, ARRAY['vanadio', 'insulina', 'diabetes', 'performance']),

-- SILÍCIO
('SILICIO', 'SILÍCIO 10mg',
 ARRAY['Silício Orgânico 10mg'],
 '1 cápsula ao dia',
 ARRAY['Saúde óssea', 'Pele e cabelos', 'Unhas fortes', 'Tecido conjuntivo'],
 ARRAY['Cálculos renais'],
 'minerais', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/10B981/FFFFFF?text=SILÍCIO',
 99.90, 49.90,
 'Silício orgânico para beleza e estrutura óssea.',
 110, ARRAY['silicio', 'ossos', 'cabelo', 'pele']),

-- BORO
('BORO', 'BORO 3mg',
 ARRAY['Boro Quelado 3mg'],
 '1 cápsula ao dia',
 ARRAY['Saúde óssea', 'Metabolismo de cálcio e magnésio', 'Função cognitiva', 'Hormônios'],
 ARRAY['Gravidez e lactação (doses altas)'],
 'minerais', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/8B5CF6/FFFFFF?text=BORO',
 79.90, 39.90,
 'Boro para ossos fortes e equilíbrio mineral.',
 130, ARRAY['boro', 'ossos', 'calcio', 'hormônios']),

-- FÓSFORO
('FOSFORO', 'FÓSFORO 500mg',
 ARRAY['Fosfato de Cálcio 500mg (fornece 230mg de fósforo)'],
 '1 cápsula ao dia',
 ARRAY['Saúde óssea e dental', 'Produção de energia (ATP)', 'Função celular', 'pH sanguíneo'],
 ARRAY['Insuficiência renal'],
 'minerais', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/EF4444/FFFFFF?text=FÓSFORO',
 79.90, 39.90,
 'Fósforo para energia celular e estrutura óssea.',
 140, ARRAY['fosforo', 'ossos', 'energia', 'celulas']),

-- POTÁSSIO
('POTASSIO', 'POTÁSSIO 99mg',
 ARRAY['Cloreto de Potássio 99mg'],
 '1 cápsula 2x ao dia',
 ARRAY['Pressão arterial saudável', 'Função muscular', 'Equilíbrio hídrico', 'Função nervosa'],
 ARRAY['Insuficiência renal', 'Hipercalemia'],
 'minerais', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/F59E0B/FFFFFF?text=POTÁSSIO',
 79.90, 39.90,
 'Potássio para pressão arterial, músculos e hidratação.',
 180, ARRAY['potassio', 'pressao', 'musculos', 'hidratacao']),

-- L-ARGININA
('L_ARGININA', 'L-ARGININA 500mg',
 ARRAY['L-Arginina 500mg'],
 '2 cápsulas ao dia',
 ARRAY['Produção de óxido nítrico', 'Circulação', 'Performance atlética', 'Saúde cardiovascular'],
 ARRAY['Herpes (pode desencadear surtos)'],
 'aminoacidos', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/10B981/FFFFFF?text=L-ARGININA',
 119.90, 59.90,
 'L-Arginina para circulação, pump e performance.',
 150, ARRAY['arginina', 'circulacao', 'pump', 'performance']),

-- L-CARNITINA
('L_CARNITINA', 'L-CARNITINA 500mg',
 ARRAY['L-Carnitina Tartarato 500mg'],
 '2 cápsulas antes do treino',
 ARRAY['Queima de gordura', 'Energia', 'Performance', 'Recuperação'],
 ARRAY['Hipotireoidismo não tratado'],
 'aminoacidos', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/8B5CF6/FFFFFF?text=L-CARNITINA',
 129.90, 64.90,
 'L-Carnitina para transporte de gorduras e energia.',
 140, ARRAY['carnitina', 'gordura', 'energia', 'treino']),

-- TAURINA
('TAURINA', 'TAURINA 500mg',
 ARRAY['Taurina 500mg'],
 '1 cápsula 2x ao dia',
 ARRAY['Saúde cardiovascular', 'Performance', 'Função nervosa', 'Hidratação celular'],
 ARRAY['Transtorno bipolar'],
 'aminoacidos', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/EF4444/FFFFFF?text=TAURINA',
 99.90, 49.90,
 'Taurina para coração, cérebro e performance.',
 160, ARRAY['taurina', 'cardiovascular', 'performance', 'nervoso']),

-- L-LISINA
('LISINA', 'L-LISINA 500mg',
 ARRAY['L-Lisina 500mg'],
 '2 cápsulas ao dia',
 ARRAY['Previne herpes', 'Absorção de cálcio', 'Produção de colágeno', 'Imunidade'],
 ARRAY['Doença renal'],
 'aminoacidos', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/F59E0B/FFFFFF?text=L-LISINA',
 99.90, 49.90,
 'L-Lisina para imunidade, ossos e prevenção de herpes.',
 130, ARRAY['lisina', 'herpes', 'colageno', 'imunidade']),

-- NAC
('NAC', 'N-ACETIL CISTEÍNA (NAC) 600mg',
 ARRAY['N-Acetil Cisteína 600mg'],
 '1 cápsula ao dia',
 ARRAY['Detox hepático', 'Antioxidante', 'Saúde respiratória', 'Produção de glutationa'],
 ARRAY['Úlcera péptica ativa'],
 'antioxidantes', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/10B981/FFFFFF?text=NAC',
 139.90, 69.90,
 'NAC precursor de glutationa para detox e proteção celular.',
 120, ARRAY['nac', 'detox', 'figado', 'antioxidante']),

-- RESVERATROL
('RESVERATROL', 'RESVERATROL 200mg',
 ARRAY['Trans-resveratrol 200mg'],
 '1 cápsula ao dia',
 ARRAY['Anti-envelhecimento', 'Cardiovascular', 'Antioxidante potente', 'Longevidade'],
 ARRAY['Distúrbios de coagulação'],
 'antioxidantes', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/8B5CF6/FFFFFF?text=RESVERATROL',
 159.90, 79.90,
 'Resveratrol de uvas para longevidade e proteção cardiovascular.',
 100, ARRAY['resveratrol', 'longevidade', 'cardiovascular', 'antioxidante']),

-- AÇAÍ
('ACAI', 'AÇAÍ 500mg',
 ARRAY['Extrato de Açaí 500mg', 'Padronizado em antocianinas'],
 '2 cápsulas ao dia',
 ARRAY['Antioxidante poderoso', 'Energia', 'Imunidade', 'Anti-inflamatório'],
 ARRAY['Alergia a frutas vermelhas'],
 'superalimentos', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/EF4444/FFFFFF?text=AÇAÍ',
 119.90, 59.90,
 'Açaí amazônico rico em antioxidantes e energia.',
 140, ARRAY['acai', 'antioxidante', 'energia', 'superalimento']),

-- MACA VERMELHA
('MACA_PERUANA_VERMELHA', 'MACA PERUANA VERMELHA 500mg',
 ARRAY['Maca Vermelha 500mg'],
 '2 cápsulas ao dia',
 ARRAY['Saúde da próstata', 'Energia', 'Densidade óssea', 'Hormônios'],
 ARRAY['Câncer de próstata'],
 'energia', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/F59E0B/FFFFFF?text=MACA+VERMELHA',
 149.90, 74.90,
 'Maca Vermelha específica para saúde masculina e próstata.',
 110, ARRAY['maca_vermelha', 'prostata', 'masculino', 'energia']),

-- BERBERINA
('BERBERINA', 'BERBERINA 500mg',
 ARRAY['Berberina HCl 500mg'],
 '1 cápsula 2x ao dia com refeições',
 ARRAY['Controle glicêmico', 'Sensibilidade à insulina', 'Colesterol', 'Emagrecimento'],
 ARRAY['Gravidez', 'Lactação', 'Hipoglicemia'],
 'metabolismo', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/10B981/FFFFFF?text=BERBERINA',
 159.90, 79.90,
 'Berberina para controle metabólico e glicêmico avançado.',
 90, ARRAY['berberina', 'diabetes', 'metabolismo', 'insulina']),

-- RHODIOLA
('RHODIOLA', 'RHODIOLA ROSEA 500mg',
 ARRAY['Extrato de Rhodiola 500mg', 'Padronizado 3% rosavinas'],
 '1 cápsula ao dia pela manhã',
 ARRAY['Combate fadiga', 'Melhora foco', 'Reduz estresse', 'Performance física'],
 ARRAY['Transtorno bipolar', 'Gravidez'],
 'adaptogenos', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/8B5CF6/FFFFFF?text=RHODIOLA',
 139.90, 69.90,
 'Rhodiola adaptógeno para energia mental e física.',
 110, ARRAY['rhodiola', 'fadiga', 'foco', 'adaptogeno']),

-- GINSENG
('GINSENG', 'GINSENG PANAX 500mg',
 ARRAY['Extrato de Ginseng Panax 500mg', 'Padronizado 7% ginsenosídeos'],
 '1 cápsula ao dia',
 ARRAY['Energia', 'Cognição', 'Imunidade', 'Performance sexual'],
 ARRAY['Hipertensão não controlada', 'Insônia'],
 'adaptogenos', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/EF4444/FFFFFF?text=GINSENG',
 149.90, 74.90,
 'Ginseng Panax premium para vitalidade e longevidade.',
 100, ARRAY['ginseng', 'energia', 'cognição', 'vitalidade']),

-- CORDYCEPS
('CORDYCEPS', 'CORDYCEPS 500mg',
 ARRAY['Extrato de Cordyceps sinensis 500mg'],
 '2 cápsulas ao dia',
 ARRAY['Performance atlética', 'Energia', 'Função pulmonar', 'Libido'],
 ARRAY['Doenças autoimunes'],
 'performance', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/F59E0B/FFFFFF?text=CORDYCEPS',
 169.90, 84.90,
 'Cordyceps cogumelo medicinal para performance e vitalidade.',
 80, ARRAY['cordyceps', 'performance', 'energia', 'libido']),

-- LION'S MANE
('LION_MANE', 'LION''S MANE 500mg',
 ARRAY['Extrato de Hericium erinaceus 500mg'],
 '2 cápsulas ao dia',
 ARRAY['Memória', 'Foco', 'Neuroproteção', 'Regeneração nervosa'],
 ARRAY['Alergia a cogumelos'],
 'cognicao', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/10B981/FFFFFF?text=LION''S+MANE',
 159.90, 79.90,
 'Lion''s Mane para saúde cerebral e função cognitiva.',
 90, ARRAY['lions_mane', 'memoria', 'foco', 'cerebro']);

-- Verificar se os dados foram inseridos
SELECT COUNT(*) as total_suplementos FROM public.supplements;
SELECT name, category, is_approved FROM public.supplements ORDER BY name LIMIT 10;
