-- ========================================
-- SOFIA - DOENÇAS E CONDIÇÕES
-- "FAÇA DE SEU ALIMENTO SEU REMÉDIO"
-- ABORDAGEM NUTRICIONAL COMPLETA
-- ========================================

-- INSERIR DOENÇAS E CONDIÇÕES COM ABORDAGEM NUTRICIONAL
INSERT INTO doencas_condicoes (nome, categoria, descricao, sintomas, causas, fatores_risco, complicacoes, exames_diagnostico, tratamentos_convencionais, abordagem_nutricional, alimentos_beneficos, alimentos_evitar, suplementos_recomendados, estilo_vida) VALUES

-- DOENÇAS CARDIOVASCULARES
('Hipertensão Arterial', 'Cardiovascular', 'Pressão arterial elevada persistentemente', ARRAY['Dor de cabeça', 'Tontura', 'Fadiga', 'Dores no peito'], ARRAY['Genética', 'Obesidade', 'Sedentarismo', 'Estresse'], ARRAY['Idade', 'Histórico familiar', 'Tabagismo'], ARRAY['AVC', 'Infarto', 'Insuficiência cardíaca'], ARRAY['Medição da PA', 'Eletrocardiograma'], ARRAY['Anti-hipertensivos', 'Diuréticos'], 'Dieta DASH, redução de sódio, potássio', ARRAY['Alho', 'Hawthorn', 'Ômega 3', 'Potássio'], ARRAY['Sal', 'Alimentos processados', 'Cafeína'], ARRAY['Magnésio', 'Coenzima Q10', 'Vitamina D'], ARRAY['Exercício regular', 'Meditação', 'Sono adequado']),

('Diabetes Tipo 2', 'Metabólica', 'Resistência à insulina e hiperglicemia', ARRAY['Sede excessiva', 'Fome excessiva', 'Fadiga', 'Visão turva'], ARRAY['Obesidade', 'Sedentarismo', 'Dieta inadequada'], ARRAY['Histórico familiar', 'Idade', 'Obesidade'], ARRAY['Neuropatia', 'Nefropatia', 'Retinopatia'], ARRAY['Glicemia', 'Hemoglobina glicada'], ARRAY['Metformina', 'Insulina'], 'Controle glicêmico, baixo índice glicêmico', ARRAY['Canela', 'Cromo', 'Fibras', 'Proteínas magras'], ARRAY['Açúcares', 'Carboidratos refinados'], ARRAY['Cromo', 'Magnésio', 'Ômega 3'], ARRAY['Exercício', 'Controle de peso', 'Monitoramento glicêmico']),

('Colesterol Alto', 'Cardiovascular', 'Elevação dos níveis de colesterol no sangue', ARRAY['Assintomático', 'Dor no peito', 'Fadiga'], ARRAY['Dieta rica em gorduras', 'Sedentarismo', 'Genética'], ARRAY['Obesidade', 'Histórico familiar', 'Idade'], ARRAY['Aterosclerose', 'Infarto', 'AVC'], ARRAY['Perfil lipídico'], ARRAY['Estatinas', 'Ezetimiba'], 'Dieta mediterrânea, redução de gorduras saturadas', ARRAY['Ômega 3', 'Fibras', 'Fitoesteróis', 'Aveia'], ARRAY['Gorduras saturadas', 'Gorduras trans', 'Colesterol'], ARRAY['Ômega 3', 'Fibras', 'Coenzima Q10'], ARRAY['Exercício aeróbico', 'Controle de peso', 'Parar de fumar']),

-- DOENÇAS INFLAMATÓRIAS
('Artrite Reumatoide', 'Autoimune', 'Inflamação crônica das articulações', ARRAY['Dor articular', 'Rigidez', 'Inchaço', 'Fadiga'], ARRAY['Genética', 'Fatores ambientais', 'Disbiose intestinal'], ARRAY['Sexo feminino', 'Idade', 'Tabagismo'], ARRAY['Deformidades', 'Osteoporose', 'Doença cardiovascular'], ARRAY['Fator reumatoide', 'Proteína C reativa'], ARRAY['DMARDs', 'Corticoides'], 'Dieta anti-inflamatória, ômega 3', ARRAY['Ômega 3', 'Cúrcuma', 'Gengibre', 'Antioxidantes'], ARRAY['Glúten', 'Laticínios', 'Açúcares'], ARRAY['Ômega 3', 'Vitamina D', 'Probióticos'], ARRAY['Exercício suave', 'Repouso', 'Técnicas de relaxamento']),

('Síndrome do Intestino Irritável', 'Digestiva', 'Distúrbio funcional do intestino', ARRAY['Dor abdominal', 'Alteração do hábito intestinal', 'Inchaço'], ARRAY['Stress', 'Disbiose', 'Sensibilidade alimentar'], ARRAY['Sexo feminino', 'Stress', 'Histórico de infecções'], ARRAY['Ansiedade', 'Depressão'], ARRAY['Exame clínico', 'Exclusão de outras doenças'], ARRAY['Antiespasmódicos', 'Probióticos'], 'Dieta FODMAP, probióticos', ARRAY['Probióticos', 'Fibras solúveis', 'Hortelã'], ARRAY['FODMAPs', 'Cafeína', 'Álcool'], ARRAY['Probióticos', 'Glutamina', 'Magnésio'], ARRAY['Gerenciamento de stress', 'Exercício regular', 'Sono adequado']),

('Doença de Crohn', 'Inflamatória', 'Doença inflamatória intestinal crônica', ARRAY['Dor abdominal', 'Diarréia', 'Perda de peso', 'Fadiga'], ARRAY['Genética', 'Disbiose', 'Fatores ambientais'], ARRAY['Histórico familiar', 'Tabagismo', 'Idade'], ARRAY['Fístulas', 'Obstrução', 'Câncer'], ARRAY['Colonoscopia', 'Ressonância'], ARRAY['Imunossupressores', 'Biológicos'], 'Dieta anti-inflamatória, probióticos', ARRAY['Ômega 3', 'Probióticos', 'Glutamina', 'Vitamina D'], ARRAY['Fibras insolúveis', 'Laticínios', 'Glúten'], ARRAY['Ômega 3', 'Vitamina D', 'Probióticos'], ARRAY['Gerenciamento de stress', 'Exercício moderado', 'Sono adequado']),

-- DOENÇAS NEURODEGENERATIVAS
('Doença de Alzheimer', 'Neurológica', 'Degeneração progressiva do cérebro', ARRAY['Perda de memória', 'Confusão', 'Mudanças de comportamento'], ARRAY['Genética', 'Inflamação', 'Acúmulo de beta-amiloide'], ARRAY['Idade', 'Histórico familiar', 'Trauma craniano'], ARRAY['Demência severa', 'Morte'], ARRAY['Testes cognitivos', 'Ressonância magnética'], ARRAY['Inibidores da colinesterase', 'Memantina'], 'Dieta MIND, antioxidantes', ARRAY['Ômega 3', 'Antioxidantes', 'Vitamina E', 'Curcumina'], ARRAY['Gorduras trans', 'Açúcares refinados'], ARRAY['Ômega 3', 'Vitamina E', 'Coenzima Q10'], ARRAY['Exercício mental', 'Socialização', 'Sono adequado']),

('Parkinson', 'Neurológica', 'Doença neurodegenerativa que afeta o movimento', ARRAY['Tremor', 'Rigidez', 'Bradicinesia', 'Instabilidade postural'], ARRAY['Genética', 'Fatores ambientais', 'Inflamação'], ARRAY['Idade', 'Histórico familiar', 'Exposição a toxinas'], ARRAY['Demência', 'Depressão', 'Pneumonia'], ARRAY['Exame neurológico', 'Ressonância magnética'], ARRAY['Levodopa', 'Agonistas dopaminérgicos'], 'Dieta rica em antioxidantes, ômega 3', ARRAY['Ômega 3', 'Antioxidantes', 'Vitamina E', 'Coenzima Q10'], ARRAY['Alimentos processados', 'Gorduras trans'], ARRAY['Ômega 3', 'Vitamina E', 'Coenzima Q10'], ARRAY['Exercício físico', 'Terapia ocupacional', 'Sono adequado']),

-- DOENÇAS HEPÁTICAS
('Esteatose Hepática', 'Hepática', 'Acúmulo de gordura no fígado', ARRAY['Fadiga', 'Dor abdominal', 'Perda de apetite'], ARRAY['Obesidade', 'Diabetes', 'Álcool'], ARRAY['Obesidade', 'Diabetes', 'Síndrome metabólica'], ARRAY['Cirrose', 'Câncer hepático'], ARRAY['Ultrassom', 'Enzimas hepáticas'], ARRAY['Mudança de estilo de vida'], 'Dieta mediterrânea, redução de carboidratos', ARRAY['Cardo mariano', 'Café', 'Ômega 3', 'Antioxidantes'], ARRAY['Álcool', 'Açúcares', 'Gorduras trans'], ARRAY['Cardo mariano', 'Vitamina E', 'Ômega 3'], ARRAY['Exercício regular', 'Controle de peso', 'Abstinência alcoólica']),

('Hepatite C', 'Hepática', 'Infecção viral do fígado', ARRAY['Fadiga', 'Dor abdominal', 'Icterícia'], ARRAY['Vírus HCV', 'Transfusão', 'Uso de drogas'], ARRAY['Transfusão antes de 1992', 'Uso de drogas', 'Tatuagens'], ARRAY['Cirrose', 'Câncer hepático'], ARRAY['Anti-HCV', 'PCR HCV'], ARRAY['Antivirais de ação direta'], 'Dieta hepatoprotetora, antioxidantes', ARRAY['Cardo mariano', 'Vitamina E', 'Ômega 3', 'Antioxidantes'], ARRAY['Álcool', 'Gorduras saturadas', 'Açúcares'], ARRAY['Cardo mariano', 'Vitamina E', 'Ômega 3'], ARRAY['Abstinência alcoólica', 'Exercício moderado', 'Sono adequado']),

-- DOENÇAS RESPIRATÓRIAS
('Asma', 'Respiratória', 'Inflamação crônica das vias aéreas', ARRAY['Tosse', 'Sibilos', 'Falta de ar', 'Aperto no peito'], ARRAY['Genética', 'Alergias', 'Poluição'], ARRAY['Histórico familiar', 'Alergias', 'Obesidade'], ARRAY['Crises severas', 'Hospitalização'], ARRAY['Espirometria', 'Testes de alergia'], ARRAY['Broncodilatadores', 'Corticoides'], 'Dieta anti-inflamatória, ômega 3', ARRAY['Ômega 3', 'Vitamina D', 'Magnésio', 'Antioxidantes'], ARRAY['Sulfitos', 'Alimentos alergênicos'], ARRAY['Vitamina D', 'Ômega 3', 'Magnésio'], ARRAY['Evitar alérgenos', 'Exercício moderado', 'Técnicas respiratórias']),

('DPOC', 'Respiratória', 'Doença pulmonar obstrutiva crônica', ARRAY['Tosse', 'Expectoração', 'Falta de ar', 'Fadiga'], ARRAY['Tabagismo', 'Poluição', 'Genética'], ARRAY['Tabagismo', 'Exposição ocupacional', 'Idade'], ARRAY['Insuficiência respiratória', 'Pneumonia'], ARRAY['Espirometria', 'Radiografia'], ARRAY['Broncodilatadores', 'Corticoides'], 'Dieta rica em antioxidantes, proteínas', ARRAY['Antioxidantes', 'Ômega 3', 'Vitamina D', 'Proteínas'], ARRAY['Alimentos que causam gases', 'Laticínios'], ARRAY['Vitamina D', 'Ômega 3', 'Antioxidantes'], ARRAY['Reabilitação pulmonar', 'Exercício moderado', 'Parar de fumar']),

-- DOENÇAS ÓSSEAS
('Osteoporose', 'Osteoarticular', 'Perda de densidade óssea', ARRAY['Fraturas', 'Dor óssea', 'Perda de altura'], ARRAY['Envelhecimento', 'Deficiência hormonal', 'Nutrição inadequada'], ARRAY['Sexo feminino', 'Idade', 'Histórico familiar'], ARRAY['Fraturas', 'Deformidades'], ARRAY['Densitometria óssea'], ARRAY['Bifosfonatos', 'Suplementação de cálcio'], 'Dieta rica em cálcio e vitamina D', ARRAY['Cálcio', 'Vitamina D', 'Vitamina K', 'Magnésio'], ARRAY['Cafeína', 'Álcool', 'Sódio excessivo'], ARRAY['Cálcio', 'Vitamina D', 'Vitamina K'], ARRAY['Exercício com peso', 'Exposição solar', 'Parar de fumar']),

('Osteoartrite', 'Osteoarticular', 'Degeneração da cartilagem articular', ARRAY['Dor articular', 'Rigidez', 'Inchaço', 'Crepitação'], ARRAY['Idade', 'Obesidade', 'Trauma'], ARRAY['Idade', 'Obesidade', 'Histórico de trauma'], ARRAY['Deformidade articular', 'Limitação funcional'], ARRAY['Radiografia', 'Ressonância magnética'], ARRAY['Analgésicos', 'Anti-inflamatórios'], 'Dieta anti-inflamatória, ômega 3', ARRAY['Ômega 3', 'Glicosamina', 'Condroitina', 'Antioxidantes'], ARRAY['Açúcares', 'Gorduras trans', 'Alimentos processados'], ARRAY['Ômega 3', 'Glicosamina', 'Vitamina D'], ARRAY['Exercício de baixo impacto', 'Controle de peso', 'Fisioterapia']),

-- DOENÇAS DA PELE
('Psoríase', 'Dermatológica', 'Doença inflamatória da pele', ARRAY['Placas vermelhas', 'Descamação', 'Coceira'], ARRAY['Genética', 'Stress', 'Disbiose intestinal'], ARRAY['Histórico familiar', 'Stress', 'Infecções'], ARRAY['Artrite psoriática', 'Doença cardiovascular'], ARRAY['Exame clínico', 'Biópsia'], ARRAY['Corticoides tópicos', 'Fototerapia'], 'Dieta anti-inflamatória, ômega 3', ARRAY['Ômega 3', 'Vitamina D', 'Probióticos', 'Antioxidantes'], ARRAY['Glúten', 'Laticínios', 'Álcool'], ARRAY['Vitamina D', 'Ômega 3', 'Probióticos'], ARRAY['Exposição solar moderada', 'Gerenciamento de stress', 'Hidratação']),

('Dermatite Atópica', 'Dermatológica', 'Doença inflamatória crônica da pele', ARRAY['Coceira', 'Vermelhidão', 'Descamação'], ARRAY['Genética', 'Alergias', 'Disbiose'], ARRAY['Histórico familiar', 'Alergias', 'Stress'], ARRAY['Infecções', 'Insônia'], ARRAY['Exame clínico', 'Testes de alergia'], ARRAY['Corticoides tópicos', 'Imunomoduladores'], 'Dieta anti-inflamatória, probióticos', ARRAY['Ômega 3', 'Probióticos', 'Vitamina D', 'Zinco'], ARRAY['Alimentos alergênicos', 'Glúten', 'Laticínios'], ARRAY['Ômega 3', 'Vitamina D', 'Probióticos'], ARRAY['Hidratação adequada', 'Evitar irritantes', 'Gerenciamento de stress']),

-- DOENÇAS MENTAIS
('Depressão', 'Mental', 'Transtorno do humor caracterizado por tristeza persistente', ARRAY['Tristeza', 'Perda de interesse', 'Fadiga', 'Alterações do sono'], ARRAY['Genética', 'Stress', 'Desequilíbrio químico'], ARRAY['Histórico familiar', 'Stress', 'Trauma'], ARRAY['Suicídio', 'Isolamento social'], ARRAY['Avaliação psiquiátrica'], ARRAY['Antidepressivos', 'Terapia'], 'Dieta mediterrânea, ômega 3, probióticos', ARRAY['Ômega 3', 'Triptofano', 'Vitamina D', 'Probióticos'], ARRAY['Açúcares', 'Álcool', 'Cafeína excessiva'], ARRAY['Ômega 3', 'Vitamina D', 'Magnésio'], ARRAY['Exercício regular', 'Terapia', 'Sono adequado']),

('Ansiedade', 'Mental', 'Transtorno caracterizado por preocupação excessiva', ARRAY['Preocupação excessiva', 'Irritabilidade', 'Insônia', 'Tensão muscular'], ARRAY['Genética', 'Stress', 'Trauma'], ARRAY['Histórico familiar', 'Stress', 'Trauma'], ARRAY['Depressão', 'Abuso de substâncias'], ARRAY['Avaliação psiquiátrica'], ARRAY['Ansiolíticos', 'Terapia'], 'Dieta rica em magnésio, ômega 3', ARRAY['Magnésio', 'Ômega 3', 'Triptofano', 'Probióticos'], ARRAY['Cafeína', 'Açúcares', 'Álcool'], ARRAY['Magnésio', 'Ômega 3', 'Vitamina D'], ARRAY['Exercício regular', 'Meditação', 'Técnicas de relaxamento']),

-- DOENÇAS METABÓLICAS
('Síndrome Metabólica', 'Metabólica', 'Conjunto de fatores de risco cardiovascular', ARRAY['Obesidade abdominal', 'Hipertensão', 'Resistência à insulina'], ARRAY['Obesidade', 'Sedentarismo', 'Dieta inadequada'], ARRAY['Idade', 'Histórico familiar', 'Sedentarismo'], ARRAY['Diabetes', 'Doença cardiovascular'], ARRAY['Medidas antropométricas', 'Exames laboratoriais'], ARRAY['Mudança de estilo de vida'], 'Dieta mediterrânea, exercício', ARRAY['Ômega 3', 'Fibras', 'Antioxidantes', 'Proteínas magras'], ARRAY['Açúcares', 'Gorduras trans', 'Carboidratos refinados'], ARRAY['Ômega 3', 'Magnésio', 'Vitamina D'], ARRAY['Exercício regular', 'Controle de peso', 'Dieta balanceada']),

('Obesidade', 'Metabólica', 'Acúmulo excessivo de gordura corporal', ARRAY['Aumento de peso', 'Fadiga', 'Dificuldade para respirar'], ARRAY['Desequilíbrio energético', 'Genética', 'Fatores ambientais'], ARRAY['Sedentarismo', 'Dieta inadequada', 'Histórico familiar'], ARRAY['Diabetes', 'Doença cardiovascular', 'Apneia'], ARRAY['IMC', 'Circunferência abdominal'], ARRAY['Mudança de estilo de vida', 'Medicamentos'], 'Dieta hipocalórica balanceada, exercício', ARRAY['Proteínas magras', 'Fibras', 'Vegetais', 'Ômega 3'], ARRAY['Açúcares', 'Gorduras trans', 'Alimentos processados'], ARRAY['Ômega 3', 'Vitamina D', 'Magnésio'], ARRAY['Exercício regular', 'Controle de porções', 'Sono adequado']),

-- DOENÇAS AUTOIMUNES
('Lúpus Eritematoso Sistêmico', 'Autoimune', 'Doença autoimune que afeta múltiplos órgãos', ARRAY['Fadiga', 'Dor articular', 'Erupção cutânea', 'Febre'], ARRAY['Genética', 'Fatores ambientais', 'Hormônios'], ARRAY['Sexo feminino', 'Histórico familiar', 'Exposição solar'], ARRAY['Nefrite', 'Doença cardiovascular', 'Infecções'], ARRAY['FAN', 'Anti-DNA', 'Complemento'], ARRAY['Imunossupressores', 'Antimaláricos'], 'Dieta anti-inflamatória, ômega 3', ARRAY['Ômega 3', 'Vitamina D', 'Antioxidantes', 'Probióticos'], ARRAY['Alfafa', 'Alimentos processados', 'Glúten'], ARRAY['Ômega 3', 'Vitamina D', 'Probióticos'], ARRAY['Proteção solar', 'Exercício moderado', 'Gerenciamento de stress']),

('Esclerose Múltipla', 'Autoimune', 'Doença autoimune que afeta o sistema nervoso', ARRAY['Fadiga', 'Fraqueza', 'Dormência', 'Problemas de visão'], ARRAY['Genética', 'Fatores ambientais', 'Infecções'], ARRAY['Histórico familiar', 'Idade', 'Sexo feminino'], ARRAY['Deficiência neurológica', 'Incapacidade'], ARRAY['Ressonância magnética', 'Punção lombar'], ARRAY['Imunomoduladores', 'Corticoides'], 'Dieta anti-inflamatória, ômega 3', ARRAY['Ômega 3', 'Vitamina D', 'Antioxidantes', 'Probióticos'], ARRAY['Gorduras saturadas', 'Alimentos processados'], ARRAY['Ômega 3', 'Vitamina D', 'Coenzima Q10'], ARRAY['Exercício adaptado', 'Fisioterapia', 'Gerenciamento de stress']),

-- DOENÇAS ENDÓCRINAS
('Hipotireoidismo', 'Endócrina', 'Deficiência de hormônios tireoidianos', ARRAY['Fadiga', 'Ganho de peso', 'Intolerância ao frio', 'Constipação'], ARRAY['Doença de Hashimoto', 'Deficiência de iodo', 'Cirurgia'], ARRAY['Sexo feminino', 'Idade', 'Histórico familiar'], ARRAY['Mixedema', 'Doença cardiovascular'], ARRAY['TSH', 'T4 livre', 'Anti-TPO'], ARRAY['Levotiroxina'], 'Dieta rica em iodo, selênio', ARRAY['Iodo', 'Selênio', 'Zinco', 'Vitamina D'], ARRAY['Goitrogênicos', 'Soja', 'Glúten'], ARRAY['Selênio', 'Zinco', 'Vitamina D'], ARRAY['Exercício regular', 'Sono adequado', 'Gerenciamento de stress']),

('Hipertireoidismo', 'Endócrina', 'Excesso de hormônios tireoidianos', ARRAY['Perda de peso', 'Taquicardia', 'Nervosismo', 'Intolerância ao calor'], ARRAY['Doença de Graves', 'Nódulos tireoidianos'], ARRAY['Sexo feminino', 'Histórico familiar', 'Stress'], ARRAY['Crise tireotóxica', 'Osteoporose'], ARRAY['TSH', 'T4 livre', 'T3'], ARRAY['Antitireoidianos', 'Betabloqueadores'], 'Dieta rica em cálcio, antioxidantes', ARRAY['Cálcio', 'Vitamina D', 'Antioxidantes', 'Ômega 3'], ARRAY['Iodo excessivo', 'Cafeína', 'Alimentos processados'], ARRAY['Cálcio', 'Vitamina D', 'Antioxidantes'], ARRAY['Exercício moderado', 'Gerenciamento de stress', 'Sono adequado']),

-- DOENÇAS RENAIS
('Doença Renal Crônica', 'Renal', 'Perda progressiva da função renal', ARRAY['Fadiga', 'Inchaço', 'Alterações urinárias', 'Náusea'], ARRAY['Diabetes', 'Hipertensão', 'Glomerulonefrite'], ARRAY['Diabetes', 'Hipertensão', 'Idade'], ARRAY['Insuficiência renal', 'Doença cardiovascular'], ARRAY['Creatinina', 'Taxa de filtração glomerular'], ARRAY['Controle da pressão', 'Diálise'], 'Dieta pobre em proteínas, sódio e potássio', ARRAY['Ômega 3', 'Vitamina D', 'Antioxidantes'], ARRAY['Proteínas excessivas', 'Sódio', 'Potássio'], ARRAY['Ômega 3', 'Vitamina D', 'Antioxidantes'], ARRAY['Controle de pressão', 'Exercício moderado', 'Sono adequado']),

-- DOENÇAS ONCOLÓGICAS
('Câncer de Mama', 'Oncológica', 'Tumor maligno da mama', ARRAY['Nódulo na mama', 'Alterações na pele', 'Dor'], ARRAY['Genética', 'Hormônios', 'Fatores ambientais'], ARRAY['Histórico familiar', 'Idade', 'Obesidade'], ARRAY['Metástase', 'Recidiva'], ARRAY['Mamografia', 'Biópsia'], ARRAY['Cirurgia', 'Quimioterapia', 'Radioterapia'], 'Dieta anti-inflamatória, antioxidantes', ARRAY['Antioxidantes', 'Ômega 3', 'Vitamina D', 'Fibras'], ARRAY['Álcool', 'Gorduras saturadas', 'Açúcares'], ARRAY['Ômega 3', 'Vitamina D', 'Antioxidantes'], ARRAY['Exercício regular', 'Controle de peso', 'Sono adequado']),

('Câncer de Próstata', 'Oncológica', 'Tumor maligno da próstata', ARRAY['Alterações urinárias', 'Dor pélvica', 'Disfunção erétil'], ARRAY['Genética', 'Idade', 'Fatores hormonais'], ARRAY['Idade', 'Histórico familiar', 'Raça'], ARRAY['Metástase', 'Recidiva'], ARRAY['PSA', 'Toque retal', 'Biópsia'], ARRAY['Cirurgia', 'Radioterapia', 'Hormonioterapia'], 'Dieta rica em antioxidantes, ômega 3', ARRAY['Licopeno', 'Ômega 3', 'Vitamina D', 'Zinco'], ARRAY['Gorduras saturadas', 'Álcool', 'Alimentos processados'], ARRAY['Ômega 3', 'Vitamina D', 'Zinco'], ARRAY['Exercício regular', 'Controle de peso', 'Sono adequado']),

-- DOENÇAS INFECCIOSAS
('Candidíase', 'Infecciosa', 'Infecção fúngica por Candida', ARRAY['Coceira', 'Corrimento', 'Dor ao urinar'], ARRAY['Candida albicans', 'Imunossupressão', 'Antibióticos'], ARRAY['Diabetes', 'Uso de antibióticos', 'Gravidez'], ARRAY['Infecção sistêmica', 'Recidivas'], ARRAY['Exame clínico', 'Cultura'], ARRAY['Antifúngicos'], 'Dieta anti-candida, probióticos', ARRAY['Probióticos', 'Alho', 'Óleo de coco', 'Chá verde'], ARRAY['Açúcares', 'Laticínios', 'Glúten'], ARRAY['Probióticos', 'Alho', 'Óleo de coco'], ARRAY['Higiene adequada', 'Roupas de algodão', 'Gerenciamento de stress']),

-- DOENÇAS ALÉRGICAS
('Rinite Alérgica', 'Alérgica', 'Inflamação alérgica da mucosa nasal', ARRAY['Espirros', 'Coriza', 'Obstrução nasal', 'Coceira'], ARRAY['Alergenos', 'Genética', 'Fatores ambientais'], ARRAY['Histórico familiar', 'Exposição a alérgenos'], ARRAY['Sinusite', 'Asma'], ARRAY['Testes de alergia', 'Exame clínico'], ARRAY['Antialérgicos', 'Corticoides'], 'Dieta anti-inflamatória, ômega 3', ARRAY['Ômega 3', 'Vitamina D', 'Probióticos', 'Quercetina'], ARRAY['Alimentos alergênicos', 'Laticínios', 'Glúten'], ARRAY['Ômega 3', 'Vitamina D', 'Probióticos'], ARRAY['Evitar alérgenos', 'Higiene nasal', 'Exercício moderado']),

-- DOENÇAS NUTRICIONAIS
('Deficiência de Vitamina D', 'Nutricional', 'Níveis inadequados de vitamina D', ARRAY['Fadiga', 'Dor óssea', 'Fraqueza muscular'], ARRAY['Baixa exposição solar', 'Dieta inadequada', 'Obesidade'], ARRAY['Pele escura', 'Idade', 'Obesidade'], ARRAY['Osteoporose', 'Doença cardiovascular'], ARRAY['25-OH vitamina D'], ARRAY['Suplementação'], 'Exposição solar, dieta rica em vitamina D', ARRAY['Peixes gordurosos', 'Gema de ovo', 'Cogumelos'], ARRAY['Alimentos processados'], ARRAY['Vitamina D3', 'Cálcio', 'Magnésio'], ARRAY['Exposição solar moderada', 'Exercício ao ar livre', 'Dieta balanceada']),

('Anemia Ferropriva', 'Nutricional', 'Deficiência de ferro no organismo', ARRAY['Fadiga', 'Palidez', 'Falta de ar', 'Tontura'], ARRAY['Dieta pobre em ferro', 'Perda sanguínea', 'Má absorção'], ARRAY['Gravidez', 'Menstruação', 'Vegetarianismo'], ARRAY['Complicações cardíacas', 'Deficiência cognitiva'], ARRAY['Hemograma', 'Ferritina'], ARRAY['Suplementação de ferro'], 'Dieta rica em ferro, vitamina C', ARRAY['Carnes vermelhas', 'Vegetais verdes', 'Vitamina C'], ARRAY['Cafeína', 'Laticínios', 'Fibras excessivas'], ARRAY['Ferro', 'Vitamina C', 'Vitamina B12'], ARRAY['Exercício moderado', 'Sono adequado', 'Dieta balanceada']); 