-- ============================================
-- SUBSTITUIR TODOS OS EXERCÍCIOS NO SUPABASE
-- Execute este SQL no Supabase SQL Editor
-- ============================================

-- 1. EXCLUIR TODOS OS EXERCÍCIOS ANTIGOS
DELETE FROM exercises_library;

-- 2. INSERIR NOVOS EXERCÍCIOS (130 exercícios organizados)
-- 🏠 CASA - PEITO + TRÍCEPS (12)
INSERT INTO exercises_library (name, description, muscle_group, difficulty, location, sets, reps, rest_time, instructions, tips, equipment_needed, is_active) VALUES
('Flexão tradicional', 'Exercício básico para peito e tríceps', 'peito', 'iniciante', 'casa', '3', '8-12', '60', '["Apoie as mãos no chão na largura dos ombros","Mantenha o corpo reto como uma prancha","Desça até o peito quase tocar o chão","Empurre de volta à posição inicial"]', '["Se for difícil, comece com joelhos no chão","Mantenha o abdômen contraído"]', '[]', true),
('Flexão inclinada', 'Flexão mais fácil com apoio elevado', 'peito', 'iniciante', 'casa', '3', '10-15', '60', '["Mãos apoiadas em superfície elevada","Corpo inclinado para cima","Desça controladamente","Empurre de volta"]', '["Quanto mais alto o apoio, mais fácil"]', '["cadeira"]', true),
('Flexão aberta', 'Foco maior no peito', 'peito', 'iniciante', 'casa', '3', '8-12', '60', '["Mãos mais abertas que a largura dos ombros","Dedos apontando levemente para fora","Desça controladamente","Foco no peito durante o movimento"]', '["Ótimo para trabalhar mais o peito"]', '[]', true),
('Flexão fechada', 'Foco no tríceps', 'tríceps', 'iniciante', 'casa', '3', '8-12', '60', '["Mãos próximas, formando um triângulo","Cotovelos junto ao corpo","Desça até o peito tocar as mãos","Empurre de volta"]', '["Foco total no tríceps"]', '[]', true),
('Tríceps banco', 'Tríceps usando cadeira', 'tríceps', 'iniciante', 'casa', '3', '10-15', '60', '["Sente na borda da cadeira","Mãos apoiadas ao lado do quadril","Deslize para frente e desça o corpo","Empurre de volta usando os tríceps"]', '["Pernas esticadas = mais difícil"]', '["cadeira"]', true),
('Isometria de flexão', 'Força estática para peito', 'peito', 'iniciante', 'casa', '3', '20-30 seg', '45', '["Posição de flexão com braços estendidos","Desça até metade do movimento","Segure a posição","Mantenha respiração controlada"]', '["Excelente para ganhar força inicial"]', '[]', true),
('Flexão diamante', 'Tríceps avançado', 'tríceps', 'intermediário', 'casa', '3', '8-12', '60', '["Mãos juntas formando um diamante","Polegares e indicadores se tocam","Desça até o peito tocar as mãos","Empurre de volta"]', '["Exercício avançado para tríceps"]', '[]', true),
('Mergulho entre cadeiras', 'Tríceps e peito intenso', 'tríceps', 'intermediário', 'casa', '3', '8-12', '90', '["Duas cadeiras paralelas","Mãos apoiadas em cada cadeira","Desça o corpo entre elas","Empurre de volta"]', '["Cuidado com a estabilidade das cadeiras"]', '["cadeira"]', true),
('Flexão hindu', 'Movimento fluido completo', 'peito', 'avançado', 'casa', '3', '8-10', '60', '["Comece em V invertido","Mergulhe para frente passando rente ao chão","Suba arqueando as costas","Volte à posição inicial"]', '["Movimento fluido e contínuo"]', '[]', true),
('Flexão explosiva', 'Potência muscular', 'peito', 'expert', 'casa', '3', '6-10', '90', '["Flexão tradicional","Empurre com força para decolar do chão","Aterrisse suavemente","Repita imediatamente"]', '["Desenvolve potência muscular"]', '[]', true),
('Flexão com palmas', 'Máxima potência', 'peito', 'expert', 'casa', '3', '5-8', '90', '["Flexão explosiva","Bata palmas no ar","Aterrisse e repita"]', '["Máxima potência"]', '[]', true),
('Flexão arqueiro', 'Preparação para um braço', 'peito', 'expert', 'casa', '3', '5-8 cada', '90', '["Mãos bem abertas","Desça para um lado, esticando o outro braço","Alterne os lados"]', '["Preparação para flexão de um braço"]', '[]', true);

-- 🏠 CASA - COSTAS + BÍCEPS (10)
INSERT INTO exercises_library (name, description, muscle_group, difficulty, location, sets, reps, rest_time, instructions, tips, equipment_needed, is_active) VALUES
('Remada invertida (mesa)', 'Costas usando mesa', 'costas', 'iniciante', 'casa', '3', '10-15', '60', '["Deite embaixo de uma mesa resistente","Segure a borda da mesa","Puxe o peito em direção à mesa","Desça controladamente"]', '["Quanto mais horizontal, mais difícil"]', '["mesa"]', true),
('Superman', 'Fortalece lombar e costas', 'costas', 'iniciante', 'casa', '3', '12-15', '45', '["Deite de barriga para baixo","Braços estendidos à frente","Levante braços e pernas simultaneamente","Segure 2-3 segundos no topo"]', '["Não force o pescoço"]', '[]', true),
('Extensão lombar', 'Fortalece a lombar', 'lombar', 'iniciante', 'casa', '3', '12-15', '45', '["Deite de barriga para baixo","Mãos atrás da cabeça","Levante o tronco do chão","Desça controladamente"]', '["Movimento suave, sem trancos"]', '[]', true),
('Rosca com garrafa', 'Bíceps com peso caseiro', 'bíceps', 'iniciante', 'casa', '3', '12-15', '60', '["Segure garrafas cheias de água/areia","Cotovelos junto ao corpo","Flexione os braços","Desça controladamente"]', '["Use garrafas de 1.5L ou 2L"]', '["garrafa"]', true),
('Remada com toalha', 'Costas usando porta', 'costas', 'iniciante', 'casa', '3', '12-15', '60', '["Amarre toalha na maçaneta","Segure as pontas e incline para trás","Puxe o corpo em direção à porta","Volte controladamente"]', '["Certifique-se que a porta está travada"]', '["toalha","porta"]', true),
('Rosca martelo', 'Bíceps e antebraço', 'bíceps', 'intermediário', 'casa', '3', '10-12', '60', '["Segure peso com pegada neutra","Flexione alternando os braços","Mantenha cotovelos fixos"]', '["Trabalha também o antebraço"]', '["garrafa"]', true),
('Barra fixa pronada', 'Costas e bíceps avançado', 'costas', 'avançado', 'casa', '3', '5-10', '90', '["Pegada pronada (palmas para frente)","Puxe até o queixo passar a barra","Desça controladamente"]', '["Se não conseguir, faça negativas"]', '["barra de porta"]', true),
('Barra fixa supinada', 'Foco no bíceps', 'bíceps', 'avançado', 'casa', '3', '5-10', '90', '["Pegada supinada (palmas para você)","Puxe até o queixo passar a barra","Foco no bíceps"]', '["Mais fácil que pronada"]', '["barra de porta"]', true),
('Barra negativa', 'Ganho de força', 'costas', 'expert', 'casa', '3', '5-8', '90', '["Suba com ajuda (pule ou use cadeira)","Desça em 5-8 segundos","Foco na fase negativa"]', '["Excelente para ganhar força para barra"]', '["barra de porta"]', true),
('Barra fixa isométrica', 'Força estática', 'costas', 'expert', 'casa', '3', '20-30 seg', '90', '["Suba até o queixo passar a barra","Segure a posição","Mantenha o máximo possível"]', '["Desenvolve força estática"]', '["barra de porta"]', true);

-- 🏠 CASA - PERNAS (11)
INSERT INTO exercises_library (name, description, muscle_group, difficulty, location, sets, reps, rest_time, instructions, tips, equipment_needed, is_active) VALUES
('Agachamento livre', 'Base para pernas', 'quadríceps', 'iniciante', 'casa', '3', '15-20', '60', '["Pés na largura dos ombros","Desça como se fosse sentar","Coxas paralelas ao chão","Empurre pelos calcanhares"]', '["Joelhos acompanham a direção dos pés"]', '[]', true),
('Afundo', 'Quadríceps e glúteos', 'quadríceps', 'iniciante', 'casa', '3', '10-12 cada', '60', '["Dê um passo à frente","Desça até o joelho de trás quase tocar o chão","Joelho da frente não passa da ponta do pé","Empurre de volta"]', '["Mantenha o tronco ereto"]', '[]', true),
('Wall sit', 'Resistência de quadríceps', 'quadríceps', 'iniciante', 'casa', '3', '30-60 seg', '60', '["Costas na parede","Desça até coxas paralelas ao chão","Joelhos a 90 graus","Segure a posição"]', '["Excelente para resistência"]', '["parede"]', true),
('Step up', 'Subida no degrau', 'quadríceps', 'iniciante', 'casa', '3', '12-15 cada', '60', '["Suba em um degrau/banco","Empurre com a perna de cima","Desça controladamente","Alterne as pernas"]', '["Quanto mais alto, mais difícil"]', '["escada"]', true),
('Panturrilha no degrau', 'Panturrilha completa', 'panturrilha', 'iniciante', 'casa', '3', '15-20', '45', '["Apoie a ponta dos pés no degrau","Calcanhares para fora do degrau","Suba na ponta dos pés","Desça abaixo do nível do degrau"]', '["Amplitude completa é essencial"]', '["escada"]', true),
('Agachamento búlgaro', 'Glúteos intenso', 'glúteos', 'intermediário', 'casa', '3', '10-12 cada', '90', '["Pé de trás apoiado em cadeira/banco","Desça até joelho de trás quase tocar o chão","Empurre pela perna da frente"]', '["Excelente para glúteos"]', '["cadeira"]', true),
('Stiff unilateral', 'Posterior e equilíbrio', 'posterior', 'intermediário', 'casa', '3', '10-12 cada', '60', '["Apoie em uma perna só","Incline o tronco para frente","Perna de trás sobe","Sinta o alongamento na posterior"]', '["Equilíbrio é fundamental"]', '[]', true),
('Salto agachado', 'Potência de pernas', 'quadríceps', 'avançado', 'casa', '3', '10-15', '90', '["Agachamento normal","Salte explosivamente","Aterrisse suavemente","Repita imediatamente"]', '["Desenvolve potência"]', '[]', true),
('Pistol assistido', 'Preparação para pistol', 'quadríceps', 'avançado', 'casa', '3', '5-8 cada', '90', '["Segure em uma porta ou cadeira","Uma perna estendida à frente","Desça em uma perna só","Use o apoio para ajudar"]', '["Preparação para pistol squat"]', '["porta"]', true),
('Pistol squat', 'Agachamento unilateral', 'quadríceps', 'expert', 'casa', '3', '3-5 cada', '90', '["Uma perna estendida à frente","Desça em uma perna só","Toque o glúteo no calcanhar","Suba sem apoio"]', '["Exercício de calistenia avançado"]', '[]', true),
('Nordic curl', 'Posterior avançado', 'posterior', 'expert', 'casa', '3', '5-8', '90', '["Ajoelhe com pés presos","Desça o corpo para frente lentamente","Use as mãos para amortecer","Volte usando o posterior"]', '["Exercício muito avançado"]', '["sofá"]', true);

-- 🏠 CASA - OMBRO + ABDÔMEN (12)
INSERT INTO exercises_library (name, description, muscle_group, difficulty, location, sets, reps, rest_time, instructions, tips, equipment_needed, is_active) VALUES
('Prancha', 'Base de core', 'abdômen', 'iniciante', 'casa', '3', '30-60 seg', '45', '["Apoie antebraços e pontas dos pés","Corpo reto como uma tábua","Abdômen contraído","Não deixe o quadril subir ou descer"]', '["Base de todo treino de core"]', '[]', true),
('Crunch', 'Abdominal básico', 'abdômen', 'iniciante', 'casa', '3', '15-20', '45', '["Deite com joelhos dobrados","Mãos atrás da cabeça","Levante os ombros do chão","Contraia o abdômen no topo"]', '["Não puxe o pescoço"]', '[]', true),
('Prancha lateral', 'Oblíquos', 'oblíquos', 'iniciante', 'casa', '3', '20-30 seg cada', '45', '["Apoie um antebraço e lateral do pé","Corpo reto, quadril elevado","Mantenha a posição","Troque de lado"]', '["Trabalha os oblíquos"]', '[]', true),
('Abdominal infra', 'Abdômen inferior', 'abdômen', 'iniciante', 'casa', '3', '12-15', '45', '["Deite com pernas estendidas","Levante as pernas até 90 graus","Desça controladamente","Não deixe as costas arquearem"]', '["Foco no abdômen inferior"]', '[]', true),
('Elevação lateral (garrafa)', 'Ombros com peso caseiro', 'ombros', 'iniciante', 'casa', '3', '12-15', '60', '["Segure garrafas nas mãos","Braços ao lado do corpo","Levante até altura dos ombros","Desça controladamente"]', '["Não balance o corpo"]', '["garrafa"]', true),
('Elevação de pernas', 'Abdômen inferior intenso', 'abdômen', 'intermediário', 'casa', '3', '12-15', '60', '["Deite com mãos embaixo do quadril","Pernas estendidas","Levante até 90 graus","Desça sem tocar o chão"]', '["Mantenha lombar no chão"]', '[]', true),
('Rotação russa', 'Oblíquos com peso', 'oblíquos', 'intermediário', 'casa', '3', '20 total', '60', '["Sente com joelhos dobrados","Incline o tronco para trás","Gire o tronco de um lado para outro","Toque o chão com as mãos"]', '["Pés podem ficar no chão ou elevados"]', '["garrafa"]', true),
('Pike push up', 'Ombros avançado', 'ombros', 'intermediário', 'casa', '3', '8-12', '60', '["Posição de V invertido","Quadril alto, pernas retas","Desça a cabeça em direção ao chão","Empurre de volta"]', '["Preparação para handstand"]', '[]', true),
('Handstand push up (parede)', 'Ombros expert', 'ombros', 'avançado', 'casa', '3', '5-8', '90', '["Fique de cabeça para baixo na parede","Mãos na largura dos ombros","Desça até a cabeça tocar o chão","Empurre de volta"]', '["Exercício avançado de ombros"]', '["parede"]', true),
('Abdominal V', 'Abdômen completo', 'abdômen', 'avançado', 'casa', '3', '10-12', '60', '["Deite com braços estendidos atrás","Levante pernas e tronco simultaneamente","Toque os pés com as mãos","Volte à posição inicial"]', '["Movimento explosivo"]', '[]', true),
('Elevação pernas suspenso', 'Abdômen na barra', 'abdômen', 'avançado', 'casa', '3', '8-12', '60', '["Pendure na barra","Levante as pernas até 90 graus","Desça controladamente"]', '["Não balance o corpo"]', '["barra de porta"]', true),
('Core completo', 'Circuito de core', 'core', 'expert', 'casa', '1', '5 min', '120', '["Prancha 1 min","Prancha lateral direita 30s","Prancha lateral esquerda 30s","Mountain climbers 1 min","Prancha final 1 min"]', '["Circuito completo de core"]', '[]', true);

-- 🏠 CASA - GLÚTEOS + POSTERIOR (10)
INSERT INTO exercises_library (name, description, muscle_group, difficulty, location, sets, reps, rest_time, instructions, tips, equipment_needed, is_active) VALUES
('Elevação pélvica', 'Base para glúteos', 'glúteos', 'iniciante', 'casa', '3', '15-20', '60', '["Deite com joelhos dobrados","Pés no chão, braços ao lado","Levante o quadril contraindo glúteos","Segure 2 segundos no topo"]', '["Base de todo treino de glúteos"]', '[]', true),
('Glúteo quatro apoios', 'Glúteo isolado', 'glúteos', 'iniciante', 'casa', '3', '15-20 cada', '60', '["Posição de quatro apoios","Levante uma perna para trás","Mantenha joelho a 90 graus","Contraia o glúteo no topo"]', '["Não arqueie as costas"]', '[]', true),
('Abdução de quadril deitado', 'Glúteo médio', 'glúteos', 'iniciante', 'casa', '3', '15-20 cada', '45', '["Deite de lado","Levante a perna de cima","Mantenha o corpo alinhado","Desça controladamente"]', '["Trabalha o glúteo médio"]', '[]', true),
('Coice de glúteo', 'Glúteo com chute', 'glúteos', 'iniciante', 'casa', '3', '15-20 cada', '60', '["Posição de quatro apoios","Chute uma perna para trás e para cima","Contraia o glúteo no topo","Retorne controladamente"]', '["Movimento controlado"]', '[]', true),
('Ponte unilateral', 'Glúteo intenso', 'glúteos', 'intermediário', 'casa', '3', '10-12 cada', '60', '["Elevação pélvica com uma perna só","Outra perna estendida","Levante o quadril","Desça controladamente"]', '["Dobra a intensidade"]', '[]', true),
('Afundo reverso', 'Glúteo e quadríceps', 'glúteos', 'intermediário', 'casa', '3', '10-12 cada', '60', '["Dê um passo para trás","Desça até joelho quase tocar o chão","Empurre de volta","Alterne as pernas"]', '["Mais foco no glúteo que afundo frontal"]', '[]', true),
('Agachamento sumô', 'Glúteos e adutores', 'glúteos', 'intermediário', 'casa', '3', '12-15', '60', '["Pés bem abertos, pontas para fora","Desça mantendo joelhos para fora","Empurre pelos calcanhares"]', '["Trabalha mais glúteos e adutores"]', '[]', true),
('Hip thrust (sofá)', 'Melhor para glúteos', 'glúteos', 'avançado', 'casa', '3', '12-15', '90', '["Costas apoiadas no sofá","Pés no chão, joelhos dobrados","Empurre o quadril para cima","Aperte os glúteos no topo"]', '["Melhor exercício para glúteos"]', '["sofá"]', true),
('Stiff unilateral casa', 'Posterior e glúteo', 'posterior', 'avançado', 'casa', '3', '10-12 cada', '90', '["Apoie em uma perna só","Incline o tronco para frente","Perna de trás sobe","Sinta o alongamento"]', '["Equilíbrio é fundamental"]', '[]', true),
('Glúteo máximo', 'Intensidade máxima', 'glúteos', 'expert', 'casa', '3', 'Até falha', '120', '["Elevação pélvica até a falha","Descanse 10 segundos","Continue até falha novamente"]', '["Técnica de intensidade máxima"]', '[]', true);

-- 🏋️ ACADEMIA - PEITO + TRÍCEPS (15)
INSERT INTO exercises_library (name, description, muscle_group, difficulty, location, sets, reps, rest_time, instructions, tips, equipment_needed, is_active) VALUES
('Supino reto com barra', 'Exercício clássico de peito', 'peito', 'intermediário', 'academia', '4', '8-12', '90', '["Deitado no banco, pés firmes no chão","Pegada na largura dos ombros + 10cm","Desça a barra até tocar o peito","Empurre explosivamente"]', '["Escápulas retraídas, peito elevado"]', '["barra","banco"]', true),
('Supino reto com halteres', 'Maior amplitude', 'peito', 'iniciante', 'academia', '3', '10-12', '90', '["Deitado no banco, halteres na altura do peito","Empurre para cima em arco leve","Aproxime os halteres no topo","Desça controladamente"]', '["Maior amplitude que barra"]', '["halteres","banco"]', true),
('Supino inclinado com barra', 'Peito superior', 'peito', 'avançado', 'academia', '4', '8-10', '90', '["Banco inclinado a 30-45°","Pegada na largura dos ombros","Desça até tocar o peito superior","Empurre explosivamente"]', '["Foco no peito superior"]', '["barra","banco inclinado"]', true),
('Supino inclinado com halteres', 'Peito superior com amplitude', 'peito', 'intermediário', 'academia', '3', '8-12', '90', '["Banco inclinado a 30-45°","Halteres na altura do peito","Empurre para cima","Desça controladamente"]', '["Maior amplitude de movimento"]', '["halteres","banco inclinado"]', true),
('Crucifixo reto', 'Isolamento de peito', 'peito', 'iniciante', 'academia', '3', '12-15', '60', '["Deitado no banco, halteres acima do peito","Cotovelos levemente flexionados","Abra os braços até sentir alongamento","Junte os halteres acima do peito"]', '["Foco no alongamento e contração"]', '["halteres","banco"]', true),
('Crucifixo inclinado', 'Peito superior isolado', 'peito', 'intermediário', 'academia', '3', '10-12', '60', '["Banco inclinado a 30-45°","Halteres acima do peito","Abra os braços mantendo cotovelos flexionados","Junte os halteres no topo"]', '["Foco no peito superior"]', '["halteres","banco inclinado"]', true),
('Peck deck (voador)', 'Isolamento na máquina', 'peito', 'iniciante', 'academia', '3', '12-15', '60', '["Sentado na máquina, costas apoiadas","Cotovelos na altura dos ombros","Junte os braços à frente","Retorne controladamente"]', '["Excelente para isolar o peito"]', '["máquina"]', true),
('Cross over alto', 'Peito inferior', 'peito', 'avançado', 'academia', '3', '12-15', '60', '["Polias na posição alta","Puxe os cabos para baixo e para frente","Junte as mãos na frente do corpo","Retorne controladamente"]', '["Trabalha a parte inferior do peito"]', '["polia","cross"]', true),
('Cross over baixo', 'Peito superior', 'peito', 'intermediário', 'academia', '3', '12-15', '60', '["Polias na posição baixa","Puxe os cabos para cima e para frente","Junte as mãos na altura do peito","Retorne controladamente"]', '["Trabalha a parte superior do peito"]', '["polia","cross"]', true),
('Supino máquina', 'Ideal para iniciantes', 'peito', 'iniciante', 'academia', '3', '12-15', '60', '["Ajuste o banco para os pegadores ficarem na linha do peito","Costas apoiadas, peito elevado","Empurre sem travar os cotovelos","Retorne controladamente"]', '["Ideal para iniciantes"]', '["máquina"]', true),
('Tríceps na polia', 'Tríceps básico', 'tríceps', 'iniciante', 'academia', '3', '12-15', '60', '["Polia alta, pegada pronada","Cotovelos fixos ao lado do corpo","Estenda os braços completamente","Retorne controladamente"]', '["Não mova os cotovelos"]', '["polia"]', true),
('Tríceps corda', 'Tríceps com corda', 'tríceps', 'intermediário', 'academia', '3', '12-15', '60', '["Polia alta com corda","Cotovelos fixos ao lado do corpo","Estenda e abra as mãos no final","Retorne controladamente"]', '["Abrir as mãos no final aumenta a contração"]', '["polia","corda"]', true),
('Tríceps testa', 'Tríceps deitado', 'tríceps', 'intermediário', 'academia', '3', '10-12', '60', '["Deitado no banco, barra acima do peito","Desça a barra em direção à testa","Estenda os braços","Mantenha cotovelos fixos"]', '["Movimento apenas dos antebraços"]', '["barra","banco"]', true),
('Tríceps francês', 'Tríceps unilateral', 'tríceps', 'intermediário', 'academia', '3', '10-12 cada', '60', '["Halter atrás da cabeça com uma mão","Cotovelo apontando para cima","Estenda o braço","Desça controladamente"]', '["Use a outra mão para estabilizar"]', '["halteres"]', true),
('Mergulho nas paralelas', 'Tríceps e peito', 'tríceps', 'intermediário', 'academia', '3', '8-12', '90', '["Apoie nas paralelas, braços esticados","Incline o tronco para frente (foco peito)","Desça até 90° de flexão","Empurre para cima"]', '["Mais inclinação = mais peito"]', '["paralelas"]', true);

-- 🏋️ ACADEMIA - COSTAS + BÍCEPS (15)
INSERT INTO exercises_library (name, description, muscle_group, difficulty, location, sets, reps, rest_time, instructions, tips, equipment_needed, is_active) VALUES
('Puxada frontal aberta', 'Costas largura', 'costas', 'intermediário', 'academia', '4', '10-12', '90', '["Sentado, coxas travadas no apoio","Pegada aberta (mais que largura dos ombros)","Puxe a barra até a altura do peito","Aperte as escápulas no final"]', '["Não balance o tronco"]', '["polia"]', true),
('Puxada frontal fechada', 'Centro das costas', 'costas', 'iniciante', 'academia', '3', '10-12', '60', '["Pegada fechada (triângulo)","Puxe até o peito","Aperte as escápulas","Retorne controladamente"]', '["Trabalha mais o centro das costas"]', '["polia"]', true),
('Remada baixa', 'Costas espessura', 'costas', 'iniciante', 'academia', '3', '12-15', '60', '["Sentado, pés apoiados na plataforma","Pegue a barra com braços esticados","Puxe em direção ao abdômen","Aperte as escápulas juntas"]', '["Mantenha a coluna neutra"]', '["polia","máquina"]', true),
('Remada curvada com barra', 'Costas completa', 'costas', 'intermediário', 'academia', '4', '8-12', '90', '["Inclinado para frente, costas retas","Barra pendurada nos braços","Puxe em direção ao abdômen","Desça controladamente"]', '["Mantenha a coluna neutra"]', '["barra"]', true),
('Remada unilateral', 'Corrige desequilíbrios', 'costas', 'intermediário', 'academia', '3', '10-12 cada', '60', '["Apoie joelho e mão no banco","Halter na outra mão","Puxe em direção ao quadril","Desça controladamente"]', '["Corrige desequilíbrios"]', '["halteres","banco"]', true),
('Barra fixa pronada academia', 'Costas fundamental', 'costas', 'avançado', 'academia', '4', '6-10', '90', '["Pegada pronada (palmas para frente)","Puxe até o queixo passar a barra","Desça controladamente"]', '["Exercício fundamental"]', '["barra fixa"]', true),
('Barra fixa supinada academia', 'Foco bíceps', 'bíceps', 'avançado', 'academia', '4', '6-10', '90', '["Pegada supinada (palmas para você)","Puxe até o queixo passar a barra","Foco no bíceps"]', '["Mais fácil que pronada"]', '["barra fixa"]', true),
('Remada cavalinho', 'Espessura costas', 'costas', 'intermediário', 'academia', '3', '10-12', '60', '["Apoiado na máquina","Puxe os pegadores em direção ao peito","Aperte as escápulas","Retorne controladamente"]', '["Ótimo para espessura das costas"]', '["máquina"]', true),
('Rosca direta com barra', 'Bíceps básico', 'bíceps', 'iniciante', 'academia', '3', '10-12', '60', '["Em pé, cotovelos fixos ao lado do corpo","Barra nas mãos, pegada supinada","Flexione até máxima contração","Desça controladamente"]', '["Não balance o corpo"]', '["barra"]', true),
('Rosca alternada', 'Bíceps com supinação', 'bíceps', 'iniciante', 'academia', '3', '10-12 cada', '60', '["Halteres ao lado do corpo","Flexione um braço de cada vez","Gire o punho durante o movimento","Alterne os braços"]', '["Supinação aumenta a ativação"]', '["halteres"]', true),
('Rosca martelo academia', 'Bíceps e braquial', 'bíceps', 'intermediário', 'academia', '3', '10-12', '60', '["Halteres ao lado do corpo, pegada neutra","Flexione mantendo pegada neutra","Suba até contração máxima","Desça controladamente"]', '["Trabalha também o braquial"]', '["halteres"]', true),
('Rosca Scott', 'Bíceps isolado', 'bíceps', 'intermediário', 'academia', '3', '10-12', '60', '["Braços apoiados no banco Scott","Flexione a barra","Desça controladamente","Não estenda completamente"]', '["Isola o bíceps"]', '["banco scott","barra"]', true),
('Rosca inclinada', 'Alongamento bíceps', 'bíceps', 'intermediário', 'academia', '3', '10-12', '60', '["Deitado no banco inclinado","Braços pendurados","Flexione os halteres","Desça controladamente"]', '["Maior alongamento do bíceps"]', '["halteres","banco inclinado"]', true),
('Rosca 21', 'Técnica intensidade', 'bíceps', 'avançado', 'academia', '3', '21 (7+7+7)', '90', '["7 reps da parte baixa até 90°","7 reps de 90° até o topo","7 reps completas"]', '["Técnica de intensidade"]', '["barra"]', true),
('Levantamento terra romeno', 'Posterior e lombar', 'posterior', 'avançado', 'academia', '4', '8-10', '120', '["Barra na frente das coxas","Joelhos levemente flexionados","Desça empurrando o quadril para trás","Suba apertando os glúteos"]', '["Costas sempre retas"]', '["barra"]', true);

-- 🏋️ ACADEMIA - PERNAS (15)
INSERT INTO exercises_library (name, description, muscle_group, difficulty, location, sets, reps, rest_time, instructions, tips, equipment_needed, is_active) VALUES
('Agachamento livre', 'Rei dos exercícios para pernas', 'quadríceps', 'intermediário', 'academia', '4', '8-12', '120', '["Barra nas costas (trapézio)","Pés largura dos ombros","Desça até coxas paralelas","Empurre pelos calcanhares"]', '["Rei dos exercícios para pernas"]', '["barra"]', true),
('Leg press', 'Pernas na máquina', 'quadríceps', 'iniciante', 'academia', '4', '12-15', '90', '["Costas e quadril colados no encosto","Pés na plataforma, largura dos ombros","Desça até joelhos formarem 90°","Empurre pelos calcanhares"]', '["Não trave os joelhos"]', '["leg press"]', true),
('Leg press unilateral', 'Corrige desequilíbrios', 'quadríceps', 'intermediário', 'academia', '3', '10-12 cada', '90', '["Uma perna de cada vez","Desça controladamente","Empurre pelo calcanhar"]', '["Corrige desequilíbrios"]', '["leg press"]', true),
('Hack machine', 'Foco no quadríceps', 'quadríceps', 'intermediário', 'academia', '4', '10-12', '90', '["Costas apoiadas na máquina","Pés na plataforma","Desça até 90°","Empurre para cima"]', '["Foco no quadríceps"]', '["hack"]', true),
('Agachamento goblet', 'Ótimo para aprender', 'quadríceps', 'iniciante', 'academia', '3', '12-15', '60', '["Halter ou kettlebell junto ao peito","Pés na largura dos ombros","Desça como se fosse sentar","Empurre pelos calcanhares"]', '["Ótimo para aprender o movimento"]', '["halteres","kettlebell"]', true),
('Agachamento búlgaro academia', 'Excelente para glúteos', 'quadríceps', 'intermediário', 'academia', '3', '10-12 cada', '90', '["Pé de trás apoiado no banco","Desça até joelho de trás quase tocar o chão","Empurre pela perna da frente"]', '["Excelente para glúteos"]', '["banco","halteres"]', true),
('Cadeira extensora', 'Isola o quadríceps', 'quadríceps', 'iniciante', 'academia', '3', '12-15', '60', '["Sentado na máquina","Estenda as pernas","Pause no topo","Desça controladamente"]', '["Isola o quadríceps"]', '["máquina"]', true),
('Mesa flexora', 'Isola o posterior', 'posterior', 'iniciante', 'academia', '3', '12-15', '60', '["Deitado de bruços na máquina","Flexione as pernas","Pause no topo","Desça controladamente"]', '["Isola o posterior da coxa"]', '["máquina"]', true),
('Stiff', 'Posterior e glúteos', 'posterior', 'intermediário', 'academia', '3', '10-12', '90', '["Barra na frente das coxas","Joelhos levemente flexionados","Desça empurrando o quadril para trás","Sinta o alongamento no posterior"]', '["Costas sempre retas"]', '["barra","halteres"]', true),
('Afundo com halteres', 'Quadríceps e glúteos', 'quadríceps', 'iniciante', 'academia', '3', '10-12 cada', '60', '["Halteres ao lado do corpo","Dê um passo à frente","Desça até joelho de trás quase tocar o chão","Empurre para voltar"]', '["Mantenha o tronco ereto"]', '["halteres"]', true),
('Panturrilha em pé', 'Panturrilha completa', 'panturrilha', 'iniciante', 'academia', '4', '15-20', '45', '["Ombros sob os apoios","Suba na ponta dos pés","Pause no topo","Desça alongando bem"]', '["Amplitude completa é essencial"]', '["máquina"]', true),
('Panturrilha sentado', 'Trabalha o sóleo', 'panturrilha', 'iniciante', 'academia', '4', '15-20', '45', '["Sentado na máquina","Joelhos sob os apoios","Suba na ponta dos pés","Desça alongando bem"]', '["Trabalha o sóleo"]', '["máquina"]', true),
('Agachamento hack', 'Foco total no quadríceps', 'quadríceps', 'avançado', 'academia', '4', '8-10', '120', '["Costas na máquina","Pés baixos na plataforma","Desça profundo","Empurre explosivamente"]', '["Foco total no quadríceps"]', '["hack"]', true),
('Agachamento frontal', 'Mais foco no quadríceps', 'quadríceps', 'avançado', 'academia', '4', '8-10', '120', '["Barra na frente dos ombros","Cotovelos altos","Desça mantendo tronco ereto","Empurre pelos calcanhares"]', '["Mais foco no quadríceps"]', '["barra"]', true),
('Passada com barra', 'Excelente para resistência', 'quadríceps', 'avançado', 'academia', '3', '10-12 cada', '90', '["Barra nas costas","Dê passos alternados","Desça até joelho quase tocar o chão","Continue caminhando"]', '["Excelente para resistência"]', '["barra"]', true);

-- 🏋️ ACADEMIA - OMBRO + ABDÔMEN (15)
INSERT INTO exercises_library (name, description, muscle_group, difficulty, location, sets, reps, rest_time, instructions, tips, equipment_needed, is_active) VALUES
('Desenvolvimento máquina', 'Ombros na máquina', 'ombros', 'iniciante', 'academia', '3', '12-15', '60', '["Sentado na máquina, costas apoiadas","Pegadores na altura dos ombros","Empurre para cima","Desça controladamente"]', '["Não trave os cotovelos"]', '["máquina"]', true),
('Desenvolvimento com halteres', 'Maior amplitude', 'ombros', 'intermediário', 'academia', '4', '10-12', '90', '["Sentado no banco, halteres na altura dos ombros","Empurre para cima","Aproxime os halteres no topo","Desça controladamente"]', '["Maior amplitude que barra"]', '["halteres","banco"]', true),
('Desenvolvimento com barra', 'Exercício clássico', 'ombros', 'avançado', 'academia', '4', '8-10', '90', '["Barra na frente do peito","Empurre para cima","Desça até altura do queixo"]', '["Exercício clássico de ombros"]', '["barra","banco"]', true),
('Elevação lateral', 'Ombros laterais', 'ombros', 'iniciante', 'academia', '3', '12-15', '60', '["Halteres ao lado do corpo","Levante até altura dos ombros","Cotovelos levemente flexionados","Desça controladamente"]', '["Não balance o corpo"]', '["halteres"]', true),
('Elevação lateral na polia', 'Tensão constante', 'ombros', 'intermediário', 'academia', '3', '12-15', '60', '["Polia baixa, pegada cruzada","Levante até altura do ombro","Desça controladamente"]', '["Tensão constante"]', '["polia"]', true),
('Elevação frontal', 'Ombros frontais', 'ombros', 'iniciante', 'academia', '3', '12-15', '60', '["Halteres na frente das coxas","Levante à frente até altura dos ombros","Desça controladamente"]', '["Alterne os braços se preferir"]', '["halteres"]', true),
('Elevação posterior', 'Ombro posterior', 'ombros', 'iniciante', 'academia', '3', '12-15', '60', '["Incline o tronco para frente","Braços pendurados","Levante para os lados","Foco no ombro posterior"]', '["Movimento controlado"]', '["halteres"]', true),
('Crucifixo invertido máquina', 'Isola ombro posterior', 'ombros', 'intermediário', 'academia', '3', '12-15', '60', '["Sentado de frente para a máquina","Abra os braços para trás","Aperte as escápulas","Retorne controladamente"]', '["Isola o ombro posterior"]', '["máquina"]', true),
('Arnold press', 'Criado por Arnold', 'ombros', 'avançado', 'academia', '3', '8-10', '90', '["Halteres na frente do rosto, palmas para você","Gire e empurre para cima","Palmas para frente no topo","Desça girando de volta"]', '["Criado por Arnold Schwarzenegger"]', '["halteres","banco"]', true),
('Remada alta', 'Ombros e trapézio', 'ombros', 'intermediário', 'academia', '3', '10-12', '60', '["Barra na frente das coxas","Puxe até altura do queixo","Cotovelos acima dos ombros","Desça controladamente"]', '["Cuidado com os ombros"]', '["barra"]', true),
('Abdominal na máquina', 'Abdômen na máquina', 'abdômen', 'iniciante', 'academia', '3', '15-20', '45', '["Sentado na máquina","Segure os pegadores","Flexione o tronco","Retorne controladamente"]', '["Foco na contração"]', '["máquina"]', true),
('Abdominal no cabo', 'Carga progressiva', 'abdômen', 'intermediário', 'academia', '3', '12-15', '60', '["Ajoelhado de frente para polia alta","Segure a corda atrás da cabeça","Flexione o tronco","Retorne controladamente"]', '["Excelente para carga progressiva"]', '["polia"]', true),
('Prancha academia', 'Base de core', 'abdômen', 'iniciante', 'academia', '3', '30-60 seg', '45', '["Apoie antebraços e pontas dos pés","Corpo reto como uma tábua","Abdômen contraído","Não deixe o quadril subir ou descer"]', '["Base de todo treino de core"]', '[]', true),
('Elevação pernas suspenso academia', 'Abdômen inferior', 'abdômen', 'avançado', 'academia', '3', '8-12', '60', '["Pendure na barra","Levante as pernas até 90 graus","Desça controladamente"]', '["Não balance o corpo"]', '["barra fixa"]', true),
('Rotação russa com anilha', 'Oblíquos com peso', 'oblíquos', 'intermediário', 'academia', '3', '20 total', '60', '["Sente com joelhos dobrados","Segure anilha com as duas mãos","Gire o tronco de um lado para outro","Toque o chão com a anilha"]', '["Pés podem ficar elevados"]', '["anilha"]', true);

-- 🏋️ ACADEMIA - GLÚTEOS + POSTERIOR (15)
INSERT INTO exercises_library (name, description, muscle_group, difficulty, location, sets, reps, rest_time, instructions, tips, equipment_needed, is_active) VALUES
('Hip thrust com barra', 'Melhor para glúteos', 'glúteos', 'intermediário', 'academia', '4', '10-12', '90', '["Costas apoiadas no banco","Barra sobre o quadril","Empurre o quadril para cima","Aperte os glúteos no topo"]', '["Melhor exercício para glúteos"]', '["barra","banco"]', true),
('Elevação pélvica academia', 'Base para glúteos', 'glúteos', 'iniciante', 'academia', '3', '15-20', '60', '["Deite com joelhos dobrados","Pés no chão, braços ao lado","Levante o quadril contraindo glúteos","Segure 2 segundos no topo"]', '["Base de todo treino de glúteos"]', '[]', true),
('Stiff academia', 'Posterior e glúteos', 'posterior', 'intermediário', 'academia', '3', '10-12', '90', '["Barra na frente das coxas","Joelhos levemente flexionados","Desça empurrando o quadril para trás","Sinta o alongamento no posterior"]', '["Costas sempre retas"]', '["barra"]', true),
('Levantamento terra romeno academia', 'Posterior completo', 'posterior', 'avançado', 'academia', '4', '8-10', '120', '["Barra na frente das coxas","Joelhos levemente flexionados","Desça empurrando o quadril para trás","Suba apertando os glúteos"]', '["Costas sempre retas"]', '["barra"]', true),
('Bom dia', 'Posterior e lombar', 'posterior', 'avançado', 'academia', '3', '10-12', '90', '["Barra nas costas","Incline o tronco para frente","Joelhos levemente flexionados","Suba apertando os glúteos"]', '["Movimento controlado"]', '["barra"]', true),
('Cadeira abdutora', 'Glúteo médio', 'glúteos', 'iniciante', 'academia', '3', '15-20', '60', '["Sentado na máquina","Abra as pernas contra a resistência","Pause no final","Retorne controladamente"]', '["Trabalha o glúteo médio"]', '["máquina"]', true),
('Cadeira adutora', 'Parte interna da coxa', 'adutores', 'iniciante', 'academia', '3', '15-20', '60', '["Sentado na máquina","Feche as pernas contra a resistência","Pause no final","Retorne controladamente"]', '["Trabalha a parte interna da coxa"]', '["máquina"]', true),
('Glúteo na polia', 'Tensão constante', 'glúteos', 'iniciante', 'academia', '3', '12-15 cada', '60', '["Caneleira presa na polia baixa","Empurre a perna para trás","Contraia o glúteo no topo","Retorne controladamente"]', '["Tensão constante"]', '["polia"]', true),
('Glúteo máquina', 'Isola o glúteo', 'glúteos', 'intermediário', 'academia', '3', '12-15 cada', '60', '["Apoiado na máquina","Empurre a plataforma para trás","Contraia o glúteo no topo","Retorne controladamente"]', '["Isola o glúteo"]', '["máquina"]', true),
('Coice na polia', 'Foco na contração', 'glúteos', 'avançado', 'academia', '3', '12-15 cada', '60', '["Caneleira na polia baixa","Empurre a perna para trás e para cima","Contraia o glúteo no topo","Retorne controladamente"]', '["Foco na contração"]', '["polia"]', true),
('Abdução na polia', 'Glúteo médio', 'glúteos', 'intermediário', 'academia', '3', '12-15 cada', '60', '["Caneleira na polia baixa","Abra a perna para o lado","Mantenha o corpo reto","Retorne controladamente"]', '["Tensão constante"]', '["polia"]', true),
('Mesa flexora academia', 'Isola posterior', 'posterior', 'iniciante', 'academia', '3', '12-15', '60', '["Deitado de bruços na máquina","Flexione as pernas","Pause no topo","Desça controladamente"]', '["Isola o posterior da coxa"]', '["máquina"]', true),
('Flexora em pé', 'Corrige desequilíbrios', 'posterior', 'intermediário', 'academia', '3', '12-15 cada', '60', '["Em pé na máquina","Flexione uma perna de cada vez","Pause no topo","Desça controladamente"]', '["Corrige desequilíbrios"]', '["máquina"]', true),
('Levantamento terra sumo', 'Glúteos e adutores', 'glúteos', 'expert', 'academia', '4', '5-8', '180', '["Pés bem abertos, pontas para fora","Pegada entre as pernas","Levante mantendo costas retas","Aperte os glúteos no topo"]', '["Foco nos glúteos e adutores"]', '["barra"]', true),
('Afundo búlgaro academia', 'Excelente para glúteos', 'glúteos', 'intermediário', 'academia', '3', '10-12 cada', '90', '["Pé de trás apoiado no banco","Desça até joelho de trás quase tocar o chão","Empurre pela perna da frente"]', '["Excelente para glúteos"]', '["banco","halteres"]', true);

-- ============================================
-- VERIFICAÇÃO FINAL
-- ============================================
-- Execute esta query para verificar:
-- SELECT location, COUNT(*) as total FROM exercises_library GROUP BY location;
-- Esperado: casa = 55, academia = 75, total = 130
