-- Script para inserir todos os 59 suplementos do JSON
-- Versão corrigida sem a coluna 'tags' que não existe na tabela

-- Primeiro, limpar dados existentes (opcional)
-- DELETE FROM public.supplements;

-- Inserir todos os suplementos
INSERT INTO public.supplements (
  name, active_ingredients, recommended_dosage, benefits, contraindications, 
  category, brand, is_approved, image_url, original_price, discount_price, 
  description, stock_quantity
) VALUES
('CART CONTROL', 
 ARRAY['Cafeína', 'Chá Verde', 'L-Carnitina', 'Cromo', 'Capsaicina'],
 '2 cápsulas 30 minutos antes do almoço',
 ARRAY['Acelera metabolismo', 'Reduz gordura abdominal', 'Controla apetite', 'Aumenta termogênese'],
 ARRAY['Hipertensão grave não controlada', 'Gravidez', 'Lactação', 'Problemas cardíacos'],
 'emagrecimento', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/4F46E5/FFFFFF?text=CART+CONTROL',
 189.90, 94.90,
 'Complexo termogênico avançado para controle de peso e aceleração metabólica.',
 150),

('A-Z COMPLEX',
 ARRAY['24 Vitaminas e Minerais', 'Vitamina A', 'Complexo B', 'Vitamina C', 'Vitamina D3', 'Vitamina E', 'Zinco', 'Selênio', 'Magnésio'],
 '1 cápsula ao dia com refeição principal',
 ARRAY['Suporte nutricional completo', 'Aumenta energia', 'Fortalece imunidade', 'Melhora concentração'],
 ARRAY['Hipervitaminose', 'Alergia a algum componente'],
 'vitaminas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/10B981/FFFFFF?text=A-Z+COMPLEX',
 89.90, 44.90,
 'Complexo vitamínico e mineral completo para suporte nutricional diário.',
 200),

('BCAA', 'BCAA',
 ARRAY['L-Leucina', 'L-Isoleucina', 'L-Valina', 'Água', 'Ácido Cítrico'],
 '1 scoop (10g) antes ou durante o treino',
 ARRAY['Preserva massa muscular', 'Reduz fadiga muscular', 'Acelera recuperação', 'Melhora performance'],
 ARRAY['Insuficiência renal', 'Fenilcetonúria'],
 'aminoacidos', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/8B5CF6/FFFFFF?text=BCAA',
 79.90, 39.90,
 'Aminoácidos de cadeia ramificada para preservação muscular e performance.',
 120),

('MACA_PERUANA', 'MACA PERUANA',
 ARRAY['Maca Peruana (Lepidium meyenii)', 'Cápsula vegetal'],
 '2 cápsulas ao dia, preferencialmente pela manhã',
 ARRAY['Aumenta libido', 'Melhora fertilidade', 'Aumenta energia', 'Regula hormônios'],
 ARRAY['Hipertireoidismo', 'Gravidez', 'Lactação'],
 'energia', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/F59E0B/FFFFFF?text=MACA+PERUANA',
 69.90, 34.90,
 'Raiz peruana tradicional para aumento de energia e libido.',
 80),

('IMUNIC', 'IMUNIC',
 ARRAY['Vitamina C', 'Zinco', 'Selênio', 'Vitamina D3', 'Equinácea', 'Própolis'],
 '1 cápsula ao dia',
 ARRAY['Fortalece sistema imunológico', 'Reduz resfriados', 'Aumenta defesas', 'Melhora resistência'],
 ARRAY['Alergia a própolis', 'Hipervitaminose'],
 'imunidade', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/EF4444/FFFFFF?text=IMUNIC',
 99.90, 49.90,
 'Complexo imunoestimulante para fortalecimento das defesas naturais.',
 90),

('CHLORELLA', 'Chlorella',
 ARRAY['Chlorella (Chlorella vulgaris)', 'Cápsula vegetal'],
 '3 cápsulas ao dia com água',
 ARRAY['Desintoxica o organismo', 'Fortalece imunidade', 'Melhora digestão', 'Aumenta energia'],
 ARRAY['Alergia a algas', 'Hipertireoidismo'],
 'detox', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/22C55E/FFFFFF?text=CHLORELLA',
 89.90, 44.90,
 'Alga unicelular rica em clorofila para desintoxicação e vitalidade.',
 100),

('COENZIMA_Q10', 'Coenzima Q10',
 ARRAY['Coenzima Q10 (Ubiquinona)', 'Óleo de girassol'],
 '1 cápsula ao dia com refeição',
 ARRAY['Melhora energia celular', 'Protege coração', 'Antioxidante', 'Retarda envelhecimento'],
 ARRAY['Uso de anticoagulantes', 'Gravidez', 'Lactação'],
 'antioxidantes', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/06B6D4/FFFFFF?text=COENZIMA+Q10',
 149.90, 74.90,
 'Coenzima essencial para produção de energia celular e proteção cardiovascular.',
 60),

('ESPIRULINA', 'Espirulina',
 ARRAY['Espirulina (Arthrospira platensis)', 'Cápsula vegetal'],
 '2 cápsulas ao dia com água',
 ARRAY['Rica em proteínas', 'Fortalece imunidade', 'Aumenta energia', 'Melhora concentração'],
 ARRAY['Alergia a algas', 'Hipertireoidismo'],
 'energia', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/84CC16/FFFFFF?text=ESPIRULINA',
 79.90, 39.90,
 'Alga azul-verde superalimento rica em proteínas e nutrientes essenciais.',
 150),

('VITAMINA_D3', 'Vitamina D3',
 ARRAY['Vitamina D3 (Colecalciferol)', 'Óleo de girassol'],
 '1 cápsula ao dia com refeição',
 ARRAY['Fortalece ossos', 'Melhora imunidade', 'Regula cálcio', 'Previne osteoporose'],
 ARRAY['Hipercalcemia', 'Hipervitaminose D'],
 'vitaminas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/F97316/FFFFFF?text=VITAMINA+D3',
 59.90, 29.90,
 'Vitamina D3 essencial para saúde óssea e sistema imunológico.',
 200),

('MAGNESIO', 'Cloreto de Magnésio',
 ARRAY['Cloreto de Magnésio', 'Água purificada'],
 '1 colher de chá (5g) dissolvida em água, 1x ao dia',
 ARRAY['Relaxa músculos', 'Melhora sono', 'Fortalece ossos', 'Reduz cãibras'],
 ARRAY['Insuficiência renal', 'Bloqueadores de cálcio'],
 'minerais', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/6366F1/FFFFFF?text=MAGNESIO',
 39.90, 19.90,
 'Cloreto de magnésio para relaxamento muscular e saúde óssea.',
 300),

('COLAGENO', 'Colágeno',
 ARRAY['Colágeno Hidrolisado', 'Vitamina C', 'Ácido Hialurônico'],
 '1 sachê ao dia dissolvido em água',
 ARRAY['Melhora pele', 'Fortalece unhas', 'Fortalece cabelos', 'Protege articulações'],
 ARRAY['Alergia a colágeno', 'Fenilcetonúria'],
 'beleza', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/EC4899/FFFFFF?text=COLAGENO',
 129.90, 64.90,
 'Colágeno hidrolisado para saúde da pele, unhas e articulações.',
 80),

('VITAMINA_K2', 'Vitamina K2 MK7',
 ARRAY['Vitamina K2 MK7', 'Óleo de girassol'],
 '1 cápsula ao dia com refeição',
 ARRAY['Fortalece ossos', 'Protege coração', 'Regula cálcio', 'Previne osteoporose'],
 ARRAY['Uso de anticoagulantes', 'Hipervitaminose K'],
 'vitaminas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/14B8A6/FFFFFF?text=VITAMINA+K2',
 89.90, 44.90,
 'Vitamina K2 MK7 para saúde óssea e cardiovascular.',
 100),

('VITAMINA_B12', 'Vitamina B12',
 ARRAY['Vitamina B12 (Cianocobalamina)', 'Cápsula vegetal'],
 '1 cápsula ao dia com água',
 ARRAY['Aumenta energia', 'Melhora concentração', 'Fortalece nervos', 'Previne anemia'],
 ARRAY['Alergia a cobalamina', 'Hipervitaminose B12'],
 'vitaminas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/3B82F6/FFFFFF?text=VITAMINA+B12',
 49.90, 24.90,
 'Vitamina B12 essencial para energia e saúde neurológica.',
 150),

('VITAMINA_A', 'Vitamina A',
 ARRAY['Vitamina A (Retinol)', 'Óleo de girassol'],
 '1 cápsula ao dia com refeição',
 ARRAY['Melhora visão', 'Fortalece imunidade', 'Protege pele', 'Antioxidante'],
 ARRAY['Hipervitaminose A', 'Gravidez', 'Lactação'],
 'vitaminas', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/DC2626/FFFFFF?text=VITAMINA+A',
 59.90, 29.90,
 'Vitamina A essencial para visão, imunidade e saúde da pele.',
 120),

('COLAGENO_SUB30', 'Colágeno SUB 30',
 ARRAY['Colágeno Hidrolisado', 'Vitamina C', 'Biotina', 'Zinco'],
 '1 sachê ao dia dissolvido em água',
 ARRAY['Antienvelhecimento', 'Melhora pele', 'Fortalece unhas', 'Fortalece cabelos'],
 ARRAY['Alergia a colágeno', 'Fenilcetonúria'],
 'beleza', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/F472B6/FFFFFF?text=COLAGENO+SUB+30',
 149.90, 74.90,
 'Colágeno hidrolisado com nutrientes para antienvelhecimento.',
 60),

('FOCUSS', 'Focuss',
 ARRAY['Ginkgo Biloba', 'Ginseng', 'Rhodiola', 'Vitamina B6', 'Taurina'],
 '1 cápsula pela manhã',
 ARRAY['Melhora concentração', 'Aumenta foco', 'Reduz estresse', 'Melhora memória'],
 ARRAY['Hipertensão', 'Uso de anticoagulantes', 'Gravidez'],
 'concentracao', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/7C3AED/FFFFFF?text=FOCUSS',
 99.90, 49.90,
 'Complexo nootrópico para melhora da concentração e foco mental.',
 70),

('IMUNI_PRO', 'İMUNİ PRO',
 ARRAY['Vitamina C', 'Zinco', 'Selênio', 'Vitamina D3', 'Equinácea', 'Própolis', 'Beta-glucana'],
 '1 cápsula ao dia',
 ARRAY['Fortalece imunidade', 'Reduz infecções', 'Aumenta defesas', 'Melhora resistência'],
 ARRAY['Alergia a própolis', 'Hipervitaminose'],
 'imunidade', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/059669/FFFFFF?text=IMUNI+PRO',
 119.90, 59.90,
 'Complexo imunoestimulante avançado para máxima proteção imunológica.',
 50),

('GELEIA_REAL', 'GELEIA REAL',
 ARRAY['Geleia Real', 'Própolis', 'Vitamina C'],
 '1 cápsula ao dia pela manhã',
 ARRAY['Aumenta energia', 'Fortalece imunidade', 'Melhora vitalidade', 'Antienvelhecimento'],
 ARRAY['Alergia a produtos apícolas', 'Gravidez', 'Lactação'],
 'energia', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/FBBF24/FFFFFF?text=GELEIA+REAL',
 89.90, 44.90,
 'Geleia real pura para aumento de energia e vitalidade.',
 80),

('IMUNI_KIDS', 'IMUNI KIDS',
 ARRAY['Vitamina C', 'Zinco', 'Vitamina D3', 'Equinácea', 'Xarope natural'],
 '1 colher de chá ao dia',
 ARRAY['Fortalece imunidade infantil', 'Reduz resfriados', 'Melhora apetite', 'Aumenta energia'],
 ARRAY['Alergia a componentes', 'Diabetes'],
 'infantil', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/10B981/FFFFFF?text=IMUNI+KIDS',
 69.90, 34.90,
 'Complexo vitamínico infantil para fortalecimento imunológico.',
 100),

('NATUOZ_BRONZE', 'NatuOz BRONZE',
 ARRAY['Óleo de Girassol Ozonizado', 'Rosa Mosqueta', 'Vitamina E'],
 'Aplicar na pele 2x ao dia',
 ARRAY['Hidratação profunda', 'Antienvelhecimento', 'Melhora textura', 'Protege do sol'],
 ARRAY['Alergia a óleos', 'Sensibilidade cutânea'],
 'beleza', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/F59E0B/FFFFFF?text=NATUOZ+BRONZE',
 79.90, 39.90,
 'Óleo ozonizado para hidratação e proteção da pele.',
 60),

('NATUOZ_BUCAL', 'NatuOz BUCAL',
 ARRAY['Óleo de Girassol Ozonizado', 'Mentol', 'Eucalipto'],
 'Aplicar na gengiva 2x ao dia',
 ARRAY['Melhora saúde bucal', 'Reduz inflamação', 'Antisséptico natural', 'Frescor'],
 ARRAY['Alergia a mentol', 'Sensibilidade bucal'],
 'saude_bucal', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/06B6D4/FFFFFF?text=NATUOZ+BUCAL',
 49.90, 24.90,
 'Óleo ozonizado para saúde bucal e higiene oral.',
 80),

('L_TRIPTOFANO', 'L-TRIPTOFANO',
 ARRAY['L-Triptofano', 'Vitamina B6', 'Magnésio'],
 '1 cápsula 30 minutos antes de dormir',
 ARRAY['Melhora sono', 'Reduz ansiedade', 'Melhora humor', 'Regula serotonina'],
 ARRAY['Uso de antidepressivos', 'Gravidez', 'Lactação'],
 'sono', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/8B5CF6/FFFFFF?text=L-TRIPTOFANO',
 79.90, 39.90,
 'L-Triptofano para melhora do sono e bem-estar mental.',
 90),

('NATUOZ_HOT', 'NatuOz HOT',
 ARRAY['Óleo de Girassol Ozonizado', 'Capsaicina', 'Mentol'],
 'Aplicar na área desejada 2x ao dia',
 ARRAY['Alívio de dores', 'Relaxamento muscular', 'Melhora circulação', 'Efeito termogênico'],
 ARRAY['Sensibilidade cutânea', 'Alergia a capsaicina'],
 'dores', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/EF4444/FFFFFF?text=NATUOZ+HOT',
 69.90, 34.90,
 'Óleo ozonizado com efeito termogênico para alívio de dores.',
 70),

('LIFE_CONTROL', 'LÍFE control',
 ARRAY['Cromo', 'Ácido Alfa-Lipóico', 'Canela', 'Gymnema Sylvestre'],
 '1 cápsula antes das refeições principais',
 ARRAY['Controla glicemia', 'Reduz apetite por doces', 'Melhora metabolismo', 'Aumenta energia'],
 ARRAY['Diabetes tipo 1', 'Gravidez', 'Lactação'],
 'glicemia', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/22C55E/FFFFFF?text=LIFE+CONTROL',
 99.90, 49.90,
 'Complexo para controle glicêmico e redução do apetite por doces.',
 80),

('OMEGA3', 'OMEGA3',
 ARRAY['Óleo de Peixe', 'EPA', 'DHA', 'Vitamina E'],
 '1 cápsula ao dia com refeição',
 ARRAY['Protege coração', 'Melhora cognição', 'Reduz inflamação', 'Fortalece imunidade'],
 ARRAY['Alergia a peixe', 'Uso de anticoagulantes'],
 'omega', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/3B82F6/FFFFFF?text=OMEGA3',
 119.90, 59.90,
 'Óleo de peixe rico em ômega-3 para saúde cardiovascular e cerebral.',
 100),

('DERMO_NATUOZ_PEELING', 'Dermo Natuoz PEELING DE CRISTAL OZONIZADO',
 ARRAY['Óleo de Girassol Ozonizado', 'Cristais de Quartzo', 'Vitamina E'],
 'Aplicar na pele 1x por semana',
 ARRAY['Esfoliação suave', 'Renovação celular', 'Melhora textura', 'Antienvelhecimento'],
 ARRAY['Sensibilidade cutânea', 'Pele irritada'],
 'beleza', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/EC4899/FFFFFF?text=PEELING+CRISTAL',
 89.90, 44.90,
 'Peeling de cristal ozonizado para renovação e rejuvenescimento da pele.',
 40),

('SHAKE_BAUNILHA', 'Shake BAUNILHA',
 ARRAY['Proteína do Soro do Leite', 'Baunilha', 'Vitamina C', 'Cálcio'],
 '1 scoop (30g) com 200ml de água ou leite',
 ARRAY['Aumenta massa muscular', 'Melhora recuperação', 'Aumenta energia', 'Fortalece ossos'],
 ARRAY['Intolerância à lactose', 'Alergia ao leite'],
 'proteina', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/F59E0B/FFFFFF?text=SHAKE+BAUNILHA',
 129.90, 64.90,
 'Shake proteico sabor baunilha para ganho de massa muscular.',
 50),

('SHAKE_CHOCOLATE', 'Shake CHOCOLATE',
 ARRAY['Proteína do Soro do Leite', 'Cacau', 'Vitamina C', 'Cálcio'],
 '1 scoop (30g) com 200ml de água ou leite',
 ARRAY['Aumenta massa muscular', 'Melhora recuperação', 'Aumenta energia', 'Fortalece ossos'],
 ARRAY['Intolerância à lactose', 'Alergia ao leite'],
 'proteina', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/8B4513/FFFFFF?text=SHAKE+CHOCOLATE',
 129.90, 64.90,
 'Shake proteico sabor chocolate para ganho de massa muscular.',
 50),

('ZMA', 'ZMA',
 ARRAY['Zinco', 'Magnésio', 'Vitamina B6'],
 '1 cápsula 30 minutos antes de dormir',
 ARRAY['Melhora sono', 'Aumenta testosterona', 'Melhora recuperação', 'Fortalece imunidade'],
 ARRAY['Insuficiência renal', 'Hipervitaminose'],
 'recuperacao', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/6366F1/FFFFFF?text=ZMA',
 79.90, 39.90,
 'Complexo ZMA para melhora do sono e recuperação muscular.',
 80),

('SLIM_CHA', 'SLIM Cha SB.',
 ARRAY['Chá Verde', 'Garcinia Cambogia', 'L-Carnitina', 'Cromo'],
 '1 cápsula 30 minutos antes das refeições',
 ARRAY['Acelera metabolismo', 'Reduz gordura', 'Controla apetite', 'Aumenta energia'],
 ARRAY['Hipertensão', 'Gravidez', 'Lactação'],
 'emagrecimento', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/22C55E/FFFFFF?text=SLIM+CHA',
 69.90, 34.90,
 'Chá verde com ingredientes termogênicos para emagrecimento.',
 100),

('PRE_TREINO_CAFE', 'NATURAL PRÉ-TREINO CAFÉ',
 ARRAY['Cafeína', 'Beta-Alanina', 'Creatina', 'Taurina', 'Vitamina B6'],
 '1 scoop 30 minutos antes do treino',
 ARRAY['Aumenta energia', 'Melhora performance', 'Reduz fadiga', 'Aumenta força'],
 ARRAY['Hipertensão', 'Problemas cardíacos', 'Gravidez'],
 'pre_treino', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/8B4513/FFFFFF?text=PRE+TREINO+CAFE',
 149.90, 74.90,
 'Pré-treino com cafeína para máxima performance e energia.',
 60),

('PICOLINATO_CROMO', 'Picolinato de Cromo',
 ARRAY['Picolinato de Cromo', 'Cápsula vegetal'],
 '1 cápsula ao dia com refeição',
 ARRAY['Controla glicemia', 'Reduz apetite', 'Melhora metabolismo', 'Aumenta energia'],
 ARRAY['Diabetes tipo 1', 'Insuficiência renal'],
 'glicemia', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/10B981/FFFFFF?text=PICOLINATO+CROMO',
 59.90, 29.90,
 'Picolinato de cromo para controle glicêmico e metabolismo.',
 120),

('CAFE_FIBRAS', 'NATURAL Café Fibras',
 ARRAY['Café Verde', 'Fibras Solúveis', 'Cromo', 'Vitamina C'],
 '1 colher de sopa ao dia com água',
 ARRAY['Aumenta saciedade', 'Melhora digestão', 'Controla glicemia', 'Aumenta energia'],
 ARRAY['Sensibilidade à cafeína', 'Problemas digestivos'],
 'fibras', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/8B4513/FFFFFF?text=CAFE+FIBRAS',
 79.90, 39.90,
 'Café com fibras para saciedade e controle glicêmico.',
 80),

('NIGHTH_CHA', 'Nighth Chá',
 ARRAY['Camomila', 'Valeriana', 'Melissa', 'Passiflora'],
 '1 xícara antes de dormir',
 ARRAY['Melhora sono', 'Relaxa', 'Reduz ansiedade', 'Melhora qualidade do sono'],
 ARRAY['Alergia a plantas', 'Gravidez', 'Lactação'],
 'sono', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/22C55E/FFFFFF?text=NIGHTH+CHA',
 49.90, 24.90,
 'Chá relaxante para melhora do sono e bem-estar.',
 100),

('SHAKE_MORANGO', 'Shake Morango',
 ARRAY['Proteína do Soro do Leite', 'Morango', 'Vitamina C', 'Cálcio'],
 '1 scoop (30g) com 200ml de água ou leite',
 ARRAY['Aumenta massa muscular', 'Melhora recuperação', 'Aumenta energia', 'Fortalece ossos'],
 ARRAY['Intolerância à lactose', 'Alergia ao leite'],
 'proteina', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/EC4899/FFFFFF?text=SHAKE+MORANGO',
 129.90, 64.90,
 'Shake proteico sabor morango para ganho de massa muscular.',
 50),

('THERMO_HEAT', 'Thermo Heat',
 ARRAY['Cafeína', 'Capsaicina', 'Gengibre', 'Cromo', 'L-Carnitina'],
 '1 cápsula 30 minutos antes das refeições',
 ARRAY['Acelera metabolismo', 'Aumenta termogênese', 'Reduz gordura', 'Aumenta energia'],
 ARRAY['Hipertensão', 'Problemas cardíacos', 'Gravidez'],
 'termogenico', 'Atlântica Natural', true,
 'https://via.placeholder.com/300x300/DC2626/FFFFFF?text=THERMO+HEAT',
 99.90, 49.90,
 'Termogênico avançado para máxima queima de gordura.',
 70);

-- Verificar se os dados foram inseridos
SELECT COUNT(*) as total_suplementos FROM public.supplements;
SELECT name, category, brand FROM public.supplements ORDER BY name;
