
-- Primeiro, atualizar o constraint para aceitar mais níveis
ALTER TABLE exercises_library DROP CONSTRAINT IF EXISTS exercises_library_difficulty_check;
ALTER TABLE exercises_library ADD CONSTRAINT exercises_library_difficulty_check CHECK (difficulty = ANY (ARRAY['facil','medio','dificil','iniciante','intermediario','avancado','expert']));

-- Agora deletar e inserir os exercícios
DELETE FROM exercises_library;

-- 🏠 CASA - PEITO + TRÍCEPS (12)
INSERT INTO exercises_library (name, description, muscle_group, difficulty, location, sets, reps, rest_time, instructions, tips, equipment_needed, is_active) VALUES
('Flexão tradicional', 'Exercício básico para peito e tríceps', 'peito', 'facil', 'casa', '3', '8-12', '60', ARRAY['Apoie as mãos no chão na largura dos ombros','Mantenha o corpo reto como uma prancha','Desça até o peito quase tocar o chão','Empurre de volta à posição inicial'], 'Se for difícil, comece com joelhos no chão.', ARRAY[]::text[], true),
('Flexão inclinada', 'Flexão mais fácil com apoio elevado', 'peito', 'facil', 'casa', '3', '10-15', '60', ARRAY['Mãos apoiadas em superfície elevada','Corpo inclinado para cima','Desça controladamente','Empurre de volta'], 'Quanto mais alto o apoio, mais fácil.', ARRAY['cadeira'], true),
('Flexão aberta', 'Foco maior no peito', 'peito', 'facil', 'casa', '3', '8-12', '60', ARRAY['Mãos mais abertas que a largura dos ombros','Dedos apontando levemente para fora','Desça controladamente','Foco no peito durante o movimento'], 'Ótimo para trabalhar mais o peito.', ARRAY[]::text[], true),
('Flexão fechada', 'Foco no tríceps', 'tríceps', 'facil', 'casa', '3', '8-12', '60', ARRAY['Mãos próximas, formando um triângulo','Cotovelos junto ao corpo','Desça até o peito tocar as mãos','Empurre de volta'], 'Foco total no tríceps.', ARRAY[]::text[], true),
('Tríceps banco', 'Tríceps usando cadeira', 'tríceps', 'facil', 'casa', '3', '10-15', '60', ARRAY['Sente na borda da cadeira','Mãos apoiadas ao lado do quadril','Deslize para frente e desça o corpo','Empurre de volta usando os tríceps'], 'Pernas esticadas = mais difícil.', ARRAY['cadeira'], true),
('Isometria de flexão', 'Força estática para peito', 'peito', 'facil', 'casa', '3', '20-30 seg', '45', ARRAY['Posição de flexão com braços estendidos','Desça até metade do movimento','Segure a posição','Mantenha respiração controlada'], 'Excelente para ganhar força inicial.', ARRAY[]::text[], true),
('Flexão diamante', 'Tríceps avançado', 'tríceps', 'medio', 'casa', '3', '8-12', '60', ARRAY['Mãos juntas formando um diamante','Polegares e indicadores se tocam','Desça até o peito tocar as mãos','Empurre de volta'], 'Exercício avançado para tríceps.', ARRAY[]::text[], true),
('Mergulho entre cadeiras', 'Tríceps e peito intenso', 'tríceps', 'medio', 'casa', '3', '8-12', '90', ARRAY['Duas cadeiras paralelas','Mãos apoiadas em cada cadeira','Desça o corpo entre elas','Empurre de volta'], 'Cuidado com a estabilidade das cadeiras.', ARRAY['cadeira'], true),
('Flexão hindu', 'Movimento fluido completo', 'peito', 'dificil', 'casa', '3', '8-10', '60', ARRAY['Comece em V invertido','Mergulhe para frente passando rente ao chão','Suba arqueando as costas','Volte à posição inicial'], 'Movimento fluido e contínuo.', ARRAY[]::text[], true),
('Flexão explosiva', 'Potência muscular', 'peito', 'dificil', 'casa', '3', '6-10', '90', ARRAY['Flexão tradicional','Empurre com força para decolar do chão','Aterrisse suavemente','Repita imediatamente'], 'Desenvolve potência muscular.', ARRAY[]::text[], true),
('Flexão com palmas', 'Máxima potência', 'peito', 'dificil', 'casa', '3', '5-8', '90', ARRAY['Flexão explosiva','Bata palmas no ar','Aterrisse e repita'], 'Máxima potência.', ARRAY[]::text[], true),
('Flexão arqueiro', 'Preparação para um braço', 'peito', 'dificil', 'casa', '3', '5-8 cada', '90', ARRAY['Mãos bem abertas','Desça para um lado, esticando o outro braço','Alterne os lados'], 'Preparação para flexão de um braço.', ARRAY[]::text[], true);

-- 🏠 CASA - COSTAS + BÍCEPS (10)
INSERT INTO exercises_library (name, description, muscle_group, difficulty, location, sets, reps, rest_time, instructions, tips, equipment_needed, is_active) VALUES
('Remada invertida (mesa)', 'Costas usando mesa', 'costas', 'facil', 'casa', '3', '10-15', '60', ARRAY['Deite embaixo de uma mesa resistente','Segure a borda da mesa','Puxe o peito em direção à mesa','Desça controladamente'], 'Quanto mais horizontal, mais difícil.', ARRAY['mesa'], true),
('Superman', 'Fortalece lombar e costas', 'costas', 'facil', 'casa', '3', '12-15', '45', ARRAY['Deite de barriga para baixo','Braços estendidos à frente','Levante braços e pernas simultaneamente','Segure 2-3 segundos no topo'], 'Não force o pescoço.', ARRAY[]::text[], true),
('Extensão lombar', 'Fortalece a lombar', 'lombar', 'facil', 'casa', '3', '12-15', '45', ARRAY['Deite de barriga para baixo','Mãos atrás da cabeça','Levante o tronco do chão','Desça controladamente'], 'Movimento suave, sem trancos.', ARRAY[]::text[], true),
('Rosca com garrafa', 'Bíceps com peso caseiro', 'bíceps', 'facil', 'casa', '3', '12-15', '60', ARRAY['Segure garrafas cheias de água/areia','Cotovelos junto ao corpo','Flexione os braços','Desça controladamente'], 'Use garrafas de 1.5L ou 2L.', ARRAY['garrafa'], true),
('Remada com toalha', 'Costas usando porta', 'costas', 'facil', 'casa', '3', '12-15', '60', ARRAY['Amarre toalha na maçaneta','Segure as pontas e incline para trás','Puxe o corpo em direção à porta','Volte controladamente'], 'Certifique-se que a porta está travada.', ARRAY['toalha','porta'], true),
('Rosca martelo', 'Bíceps e antebraço', 'bíceps', 'medio', 'casa', '3', '10-12', '60', ARRAY['Segure peso com pegada neutra','Flexione alternando os braços','Mantenha cotovelos fixos'], 'Trabalha também o antebraço.', ARRAY['garrafa'], true),
('Barra fixa pronada', 'Costas e bíceps avançado', 'costas', 'dificil', 'casa', '3', '5-10', '90', ARRAY['Pegada pronada (palmas para frente)','Puxe até o queixo passar a barra','Desça controladamente'], 'Se não conseguir, faça negativas.', ARRAY['barra de porta'], true),
('Barra fixa supinada', 'Foco no bíceps', 'bíceps', 'dificil', 'casa', '3', '5-10', '90', ARRAY['Pegada supinada (palmas para você)','Puxe até o queixo passar a barra','Foco no bíceps'], 'Mais fácil que pronada.', ARRAY['barra de porta'], true),
('Barra negativa', 'Ganho de força', 'costas', 'dificil', 'casa', '3', '5-8', '90', ARRAY['Suba com ajuda (pule ou use cadeira)','Desça em 5-8 segundos','Foco na fase negativa'], 'Excelente para ganhar força para barra.', ARRAY['barra de porta'], true),
('Barra fixa isométrica', 'Força estática', 'costas', 'dificil', 'casa', '3', '20-30 seg', '90', ARRAY['Suba até o queixo passar a barra','Segure a posição','Mantenha o máximo possível'], 'Desenvolve força estática.', ARRAY['barra de porta'], true);

-- 🏠 CASA - PERNAS (11)
INSERT INTO exercises_library (name, description, muscle_group, difficulty, location, sets, reps, rest_time, instructions, tips, equipment_needed, is_active) VALUES
('Agachamento livre', 'Base para pernas', 'quadríceps', 'facil', 'casa', '3', '15-20', '60', ARRAY['Pés na largura dos ombros','Desça como se fosse sentar','Coxas paralelas ao chão','Empurre pelos calcanhares'], 'Joelhos acompanham a direção dos pés.', ARRAY[]::text[], true),
('Afundo', 'Quadríceps e glúteos', 'quadríceps', 'facil', 'casa', '3', '10-12 cada', '60', ARRAY['Dê um passo à frente','Desça até o joelho de trás quase tocar o chão','Joelho da frente não passa da ponta do pé','Empurre de volta'], 'Mantenha o tronco ereto.', ARRAY[]::text[], true),
('Wall sit', 'Resistência de quadríceps', 'quadríceps', 'facil', 'casa', '3', '30-60 seg', '60', ARRAY['Costas na parede','Desça até coxas paralelas ao chão','Joelhos a 90 graus','Segure a posição'], 'Excelente para resistência.', ARRAY['parede'], true),
('Step up', 'Subida no degrau', 'quadríceps', 'facil', 'casa', '3', '12-15 cada', '60', ARRAY['Suba em um degrau/banco','Empurre com a perna de cima','Desça controladamente','Alterne as pernas'], 'Quanto mais alto, mais difícil.', ARRAY['escada'], true),
('Panturrilha no degrau', 'Panturrilha completa', 'panturrilha', 'facil', 'casa', '3', '15-20', '45', ARRAY['Apoie a ponta dos pés no degrau','Calcanhares para fora do degrau','Suba na ponta dos pés','Desça abaixo do nível do degrau'], 'Amplitude completa é essencial.', ARRAY['escada'], true),
('Agachamento búlgaro', 'Glúteos intenso', 'glúteos', 'medio', 'casa', '3', '10-12 cada', '90', ARRAY['Pé de trás apoiado em cadeira/banco','Desça até joelho de trás quase tocar o chão','Empurre pela perna da frente'], 'Excelente para glúteos.', ARRAY['cadeira'], true),
('Stiff unilateral', 'Posterior e equilíbrio', 'posterior', 'medio', 'casa', '3', '10-12 cada', '60', ARRAY['Apoie em uma perna só','Incline o tronco para frente','Perna de trás sobe','Sinta o alongamento na posterior'], 'Equilíbrio é fundamental.', ARRAY[]::text[], true),
('Salto agachado', 'Potência de pernas', 'quadríceps', 'dificil', 'casa', '3', '10-15', '90', ARRAY['Agachamento normal','Salte explosivamente','Aterrisse suavemente','Repita imediatamente'], 'Desenvolve potência.', ARRAY[]::text[], true),
('Pistol assistido', 'Preparação para pistol', 'quadríceps', 'dificil', 'casa', '3', '5-8 cada', '90', ARRAY['Segure em uma porta ou cadeira','Uma perna estendida à frente','Desça em uma perna só','Use o apoio para ajudar'], 'Preparação para pistol squat.', ARRAY['porta'], true),
('Pistol squat', 'Agachamento unilateral', 'quadríceps', 'dificil', 'casa', '3', '3-5 cada', '90', ARRAY['Uma perna estendida à frente','Desça em uma perna só','Toque o glúteo no calcanhar','Suba sem apoio'], 'Exercício de calistenia avançado.', ARRAY[]::text[], true),
('Nordic curl', 'Posterior avançado', 'posterior', 'dificil', 'casa', '3', '5-8', '90', ARRAY['Ajoelhe com pés presos','Desça o corpo para frente lentamente','Use as mãos para amortecer','Volte usando o posterior'], 'Exercício muito avançado.', ARRAY['sofá'], true);

-- 🏠 CASA - OMBRO + ABDÔMEN (12)
INSERT INTO exercises_library (name, description, muscle_group, difficulty, location, sets, reps, rest_time, instructions, tips, equipment_needed, is_active) VALUES
('Prancha', 'Base de core', 'abdômen', 'facil', 'casa', '3', '30-60 seg', '45', ARRAY['Apoie antebraços e pontas dos pés','Corpo reto como uma tábua','Abdômen contraído','Não deixe o quadril subir ou descer'], 'Base de todo treino de core.', ARRAY[]::text[], true),
('Crunch', 'Abdominal básico', 'abdômen', 'facil', 'casa', '3', '15-20', '45', ARRAY['Deite com joelhos dobrados','Mãos atrás da cabeça','Levante os ombros do chão','Contraia o abdômen no topo'], 'Não puxe o pescoço.', ARRAY[]::text[], true),
('Prancha lateral', 'Oblíquos', 'oblíquos', 'facil', 'casa', '3', '20-30 seg cada', '45', ARRAY['Apoie um antebraço e lateral do pé','Corpo reto, quadril elevado','Mantenha a posição','Troque de lado'], 'Trabalha os oblíquos.', ARRAY[]::text[], true),
('Abdominal infra', 'Abdômen inferior', 'abdômen', 'facil', 'casa', '3', '12-15', '45', ARRAY['Deite com pernas estendidas','Levante as pernas até 90 graus','Desça controladamente','Não deixe as costas arquearem'], 'Foco no abdômen inferior.', ARRAY[]::text[], true),
('Elevação lateral (garrafa)', 'Ombros com peso caseiro', 'ombros', 'facil', 'casa', '3', '12-15', '60', ARRAY['Segure garrafas nas mãos','Braços ao lado do corpo','Levante até altura dos ombros','Desça controladamente'], 'Não balance o corpo.', ARRAY['garrafa'], true),
('Elevação de pernas', 'Abdômen inferior intenso', 'abdômen', 'medio', 'casa', '3', '12-15', '60', ARRAY['Deite com mãos embaixo do quadril','Pernas estendidas','Levante até 90 graus','Desça sem tocar o chão'], 'Mantenha lombar no chão.', ARRAY[]::text[], true),
('Rotação russa', 'Oblíquos com peso', 'oblíquos', 'medio', 'casa', '3', '20 total', '60', ARRAY['Sente com joelhos dobrados','Incline o tronco para trás','Gire o tronco de um lado para outro','Toque o chão com as mãos'], 'Pés podem ficar no chão ou elevados.', ARRAY['garrafa'], true),
('Pike push up', 'Ombros avançado', 'ombros', 'medio', 'casa', '3', '8-12', '60', ARRAY['Posição de V invertido','Quadril alto, pernas retas','Desça a cabeça em direção ao chão','Empurre de volta'], 'Preparação para handstand.', ARRAY[]::text[], true),
('Handstand push up (parede)', 'Ombros expert', 'ombros', 'dificil', 'casa', '3', '5-8', '90', ARRAY['Fique de cabeça para baixo na parede','Mãos na largura dos ombros','Desça até a cabeça tocar o chão','Empurre de volta'], 'Exercício avançado de ombros.', ARRAY['parede'], true),
('Abdominal V', 'Abdômen completo', 'abdômen', 'dificil', 'casa', '3', '10-12', '60', ARRAY['Deite com braços estendidos atrás','Levante pernas e tronco simultaneamente','Toque os pés com as mãos','Volte à posição inicial'], 'Movimento explosivo.', ARRAY[]::text[], true),
('Elevação pernas suspenso', 'Abdômen na barra', 'abdômen', 'dificil', 'casa', '3', '8-12', '60', ARRAY['Pendure na barra','Levante as pernas até 90 graus','Desça controladamente'], 'Não balance o corpo.', ARRAY['barra de porta'], true),
('Core completo', 'Circuito de core', 'core', 'dificil', 'casa', '1', '5 min', '120', ARRAY['Prancha 1 min','Prancha lateral direita 30s','Prancha lateral esquerda 30s','Mountain climbers 1 min','Prancha final 1 min'], 'Circuito completo de core.', ARRAY[]::text[], true);

-- 🏠 CASA - GLÚTEOS + POSTERIOR (10)
INSERT INTO exercises_library (name, description, muscle_group, difficulty, location, sets, reps, rest_time, instructions, tips, equipment_needed, is_active) VALUES
('Elevação pélvica', 'Base para glúteos', 'glúteos', 'facil', 'casa', '3', '15-20', '60', ARRAY['Deite com joelhos dobrados','Pés no chão, braços ao lado','Levante o quadril contraindo glúteos','Segure 2 segundos no topo'], 'Base de todo treino de glúteos.', ARRAY[]::text[], true),
('Glúteo quatro apoios', 'Glúteo isolado', 'glúteos', 'facil', 'casa', '3', '15-20 cada', '60', ARRAY['Posição de quatro apoios','Levante uma perna para trás','Mantenha joelho a 90 graus','Contraia o glúteo no topo'], 'Não arqueie as costas.', ARRAY[]::text[], true),
('Abdução de quadril deitado', 'Glúteo médio', 'glúteos', 'facil', 'casa', '3', '15-20 cada', '45', ARRAY['Deite de lado','Levante a perna de cima','Mantenha o corpo alinhado','Desça controladamente'], 'Trabalha o glúteo médio.', ARRAY[]::text[], true),
('Coice de glúteo', 'Glúteo com chute', 'glúteos', 'facil', 'casa', '3', '15-20 cada', '60', ARRAY['Posição de quatro apoios','Chute uma perna para trás e para cima','Contraia o glúteo no topo','Retorne controladamente'], 'Movimento controlado.', ARRAY[]::text[], true),
('Ponte unilateral', 'Glúteo intenso', 'glúteos', 'medio', 'casa', '3', '10-12 cada', '60', ARRAY['Elevação pélvica com uma perna só','Outra perna estendida','Levante o quadril','Desça controladamente'], 'Dobra a intensidade.', ARRAY[]::text[], true),
('Afundo reverso', 'Glúteo e quadríceps', 'glúteos', 'medio', 'casa', '3', '10-12 cada', '60', ARRAY['Dê um passo para trás','Desça até joelho quase tocar o chão','Empurre de volta','Alterne as pernas'], 'Mais foco no glúteo que afundo frontal.', ARRAY[]::text[], true),
('Agachamento sumô', 'Glúteos e adutores', 'glúteos', 'medio', 'casa', '3', '12-15', '60', ARRAY['Pés bem abertos, pontas para fora','Desça mantendo joelhos para fora','Empurre pelos calcanhares'], 'Trabalha mais glúteos e adutores.', ARRAY[]::text[], true),
('Hip thrust (sofá)', 'Melhor para glúteos', 'glúteos', 'dificil', 'casa', '3', '12-15', '90', ARRAY['Costas apoiadas no sofá','Pés no chão, joelhos dobrados','Empurre o quadril para cima','Aperte os glúteos no topo'], 'Melhor exercício para glúteos.', ARRAY['sofá'], true),
('Stiff unilateral casa', 'Posterior e glúteo', 'posterior', 'dificil', 'casa', '3', '10-12 cada', '90', ARRAY['Apoie em uma perna só','Incline o tronco para frente','Perna de trás sobe','Sinta o alongamento'], 'Equilíbrio é fundamental.', ARRAY[]::text[], true),
('Glúteo máximo', 'Intensidade máxima', 'glúteos', 'dificil', 'casa', '3', 'Até falha', '120', ARRAY['Elevação pélvica até a falha','Descanse 10 segundos','Continue até falha novamente'], 'Técnica de intensidade máxima.', ARRAY[]::text[], true);

-- 🏋️ ACADEMIA - PEITO + TRÍCEPS (15)
INSERT INTO exercises_library (name, description, muscle_group, difficulty, location, sets, reps, rest_time, instructions, tips, equipment_needed, is_active) VALUES
('Supino reto com barra', 'Exercício clássico de peito', 'peito', 'medio', 'academia', '4', '8-12', '90', ARRAY['Deitado no banco, pés firmes no chão','Pegada na largura dos ombros + 10cm','Desça a barra até tocar o peito','Empurre explosivamente'], 'Escápulas retraídas, peito elevado.', ARRAY['barra','banco'], true),
('Supino reto com halteres', 'Maior amplitude', 'peito', 'facil', 'academia', '3', '10-12', '90', ARRAY['Deitado no banco, halteres na altura do peito','Empurre para cima em arco leve','Aproxime os halteres no topo','Desça controladamente'], 'Maior amplitude que barra.', ARRAY['halteres','banco'], true),
('Supino inclinado com barra', 'Peito superior', 'peito', 'dificil', 'academia', '4', '8-10', '90', ARRAY['Banco inclinado a 30-45°','Pegada na largura dos ombros','Desça até tocar o peito superior','Empurre explosivamente'], 'Foco no peito superior.', ARRAY['barra','banco inclinado'], true),
('Supino inclinado com halteres', 'Peito superior com amplitude', 'peito', 'medio', 'academia', '3', '8-12', '90', ARRAY['Banco inclinado a 30-45°','Halteres na altura do peito','Empurre para cima','Desça controladamente'], 'Maior amplitude de movimento.', ARRAY['halteres','banco inclinado'], true),
('Crucifixo reto', 'Isolamento de peito', 'peito', 'facil', 'academia', '3', '12-15', '60', ARRAY['Deitado no banco, halteres acima do peito','Cotovelos levemente flexionados','Abra os braços até sentir alongamento','Junte os halteres acima do peito'], 'Foco no alongamento e contração.', ARRAY['halteres','banco'], true),
('Crucifixo inclinado', 'Peito superior isolado', 'peito', 'medio', 'academia', '3', '10-12', '60', ARRAY['Banco inclinado a 30-45°','Halteres acima do peito','Abra os braços mantendo cotovelos flexionados','Junte os halteres no topo'], 'Foco no peito superior.', ARRAY['halteres','banco inclinado'], true),
('Peck deck (voador)', 'Isolamento na máquina', 'peito', 'facil', 'academia', '3', '12-15', '60', ARRAY['Sentado na máquina, costas apoiadas','Cotovelos na altura dos ombros','Junte os braços à frente','Retorne controladamente'], 'Excelente para isolar o peito.', ARRAY['máquina'], true),
('Cross over alto', 'Peito inferior', 'peito', 'dificil', 'academia', '3', '12-15', '60', ARRAY['Polias na posição alta','Puxe os cabos para baixo e para frente','Junte as mãos na frente do corpo','Retorne controladamente'], 'Trabalha a parte inferior do peito.', ARRAY['polia','cross'], true),
('Cross over baixo', 'Peito superior', 'peito', 'medio', 'academia', '3', '12-15', '60', ARRAY['Polias na posição baixa','Puxe os cabos para cima e para frente','Junte as mãos na altura do peito','Retorne controladamente'], 'Trabalha a parte superior do peito.', ARRAY['polia','cross'], true),
('Supino máquina', 'Ideal para iniciantes', 'peito', 'facil', 'academia', '3', '12-15', '60', ARRAY['Ajuste o banco para os pegadores ficarem na linha do peito','Costas apoiadas, peito elevado','Empurre sem travar os cotovelos','Retorne controladamente'], 'Ideal para iniciantes.', ARRAY['máquina'], true),
('Tríceps na polia', 'Tríceps básico', 'tríceps', 'facil', 'academia', '3', '12-15', '60', ARRAY['Polia alta, pegada pronada','Cotovelos fixos ao lado do corpo','Estenda os braços completamente','Retorne controladamente'], 'Não mova os cotovelos.', ARRAY['polia'], true),
('Tríceps corda', 'Tríceps com corda', 'tríceps', 'medio', 'academia', '3', '12-15', '60', ARRAY['Polia alta com corda','Cotovelos fixos ao lado do corpo','Estenda e abra as mãos no final','Retorne controladamente'], 'Abrir as mãos no final aumenta a contração.', ARRAY['polia','corda'], true),
('Tríceps testa', 'Tríceps deitado', 'tríceps', 'medio', 'academia', '3', '10-12', '60', ARRAY['Deitado no banco, barra acima do peito','Desça a barra em direção à testa','Estenda os braços','Mantenha cotovelos fixos'], 'Movimento apenas dos antebraços.', ARRAY['barra','banco'], true),
('Tríceps francês', 'Tríceps unilateral', 'tríceps', 'medio', 'academia', '3', '10-12 cada', '60', ARRAY['Halter atrás da cabeça com uma mão','Cotovelo apontando para cima','Estenda o braço','Desça controladamente'], 'Use a outra mão para estabilizar.', ARRAY['halteres'], true),
('Mergulho nas paralelas', 'Tríceps e peito', 'tríceps', 'medio', 'academia', '3', '8-12', '90', ARRAY['Apoie nas paralelas, braços esticados','Incline o tronco para frente (foco peito)','Desça até 90° de flexão','Empurre para cima'], 'Mais inclinação = mais peito.', ARRAY['paralelas'], true);

-- 🏋️ ACADEMIA - COSTAS + BÍCEPS (15)
INSERT INTO exercises_library (name, description, muscle_group, difficulty, location, sets, reps, rest_time, instructions, tips, equipment_needed, is_active) VALUES
('Puxada frontal aberta', 'Costas largura', 'costas', 'medio', 'academia', '4', '10-12', '90', ARRAY['Sentado, coxas travadas no apoio','Pegada aberta (mais que largura dos ombros)','Puxe a barra até a altura do peito','Aperte as escápulas no final'], 'Não balance o tronco.', ARRAY['polia'], true),
('Puxada frontal fechada', 'Centro das costas', 'costas', 'facil', 'academia', '3', '10-12', '60', ARRAY['Pegada fechada (triângulo)','Puxe até o peito','Aperte as escápulas','Retorne controladamente'], 'Trabalha mais o centro das costas.', ARRAY['polia'], true),
('Remada baixa', 'Costas espessura', 'costas', 'facil', 'academia', '3', '12-15', '60', ARRAY['Sentado, pés apoiados na plataforma','Pegue a barra com braços esticados','Puxe em direção ao abdômen','Aperte as escápulas juntas'], 'Mantenha a coluna neutra.', ARRAY['polia','máquina'], true),
('Remada curvada com barra', 'Costas completa', 'costas', 'medio', 'academia', '4', '8-12', '90', ARRAY['Inclinado para frente, costas retas','Barra pendurada nos braços','Puxe em direção ao abdômen','Desça controladamente'], 'Mantenha a coluna neutra.', ARRAY['barra'], true),
('Remada unilateral', 'Corrige desequilíbrios', 'costas', 'medio', 'academia', '3', '10-12 cada', '60', ARRAY['Apoie joelho e mão no banco','Halter na outra mão','Puxe em direção ao quadril','Desça controladamente'], 'Corrige desequilíbrios.', ARRAY['halteres','banco'], true),
('Barra fixa pronada academia', 'Costas fundamental', 'costas', 'dificil', 'academia', '4', '6-10', '90', ARRAY['Pegada pronada (palmas para frente)','Puxe até o queixo passar a barra','Desça controladamente'], 'Exercício fundamental.', ARRAY['barra fixa'], true),
('Barra fixa supinada academia', 'Foco bíceps', 'bíceps', 'dificil', 'academia', '4', '6-10', '90', ARRAY['Pegada supinada (palmas para você)','Puxe até o queixo passar a barra','Foco no bíceps'], 'Mais fácil que pronada.', ARRAY['barra fixa'], true),
('Remada cavalinho', 'Espessura costas', 'costas', 'medio', 'academia', '3', '10-12', '60', ARRAY['Apoiado na máquina','Puxe os pegadores em direção ao peito','Aperte as escápulas','Retorne controladamente'], 'Ótimo para espessura das costas.', ARRAY['máquina'], true),
('Rosca direta com barra', 'Bíceps básico', 'bíceps', 'facil', 'academia', '3', '10-12', '60', ARRAY['Em pé, cotovelos fixos ao lado do corpo','Barra nas mãos, pegada supinada','Flexione até máxima contração','Desça controladamente'], 'Não balance o corpo.', ARRAY['barra'], true),
('Rosca alternada', 'Bíceps com supinação', 'bíceps', 'facil', 'academia', '3', '10-12 cada', '60', ARRAY['Halteres ao lado do corpo','Flexione um braço de cada vez','Gire o punho durante o movimento','Alterne os braços'], 'Supinação aumenta a ativação.', ARRAY['halteres'], true),
('Rosca martelo academia', 'Bíceps e braquial', 'bíceps', 'medio', 'academia', '3', '10-12', '60', ARRAY['Halteres ao lado do corpo, pegada neutra','Flexione mantendo pegada neutra','Suba até contração máxima','Desça controladamente'], 'Trabalha também o braquial.', ARRAY['halteres'], true),
('Rosca Scott', 'Bíceps isolado', 'bíceps', 'medio', 'academia', '3', '10-12', '60', ARRAY['Braços apoiados no banco Scott','Flexione a barra','Desça controladamente','Não estenda completamente'], 'Isola o bíceps.', ARRAY['banco scott','barra'], true),
('Rosca inclinada', 'Alongamento bíceps', 'bíceps', 'medio', 'academia', '3', '10-12', '60', ARRAY['Deitado no banco inclinado','Braços pendurados','Flexione os halteres','Desça controladamente'], 'Maior alongamento do bíceps.', ARRAY['halteres','banco inclinado'], true),
('Rosca 21', 'Técnica intensidade', 'bíceps', 'dificil', 'academia', '3', '21 (7+7+7)', '90', ARRAY['7 reps da parte baixa até 90°','7 reps de 90° até o topo','7 reps completas'], 'Técnica de intensidade.', ARRAY['barra'], true),
('Levantamento terra romeno', 'Posterior e lombar', 'posterior', 'dificil', 'academia', '4', '8-10', '120', ARRAY['Barra na frente das coxas','Joelhos levemente flexionados','Desça empurrando o quadril para trás','Suba apertando os glúteos'], 'Costas sempre retas.', ARRAY['barra'], true);

-- 🏋️ ACADEMIA - PERNAS (15)
INSERT INTO exercises_library (name, description, muscle_group, difficulty, location, sets, reps, rest_time, instructions, tips, equipment_needed, is_active) VALUES
('Agachamento livre academia', 'Rei dos exercícios para pernas', 'quadríceps', 'medio', 'academia', '4', '8-12', '120', ARRAY['Barra nas costas (trapézio)','Pés largura dos ombros','Desça até coxas paralelas','Empurre pelos calcanhares'], 'Rei dos exercícios para pernas.', ARRAY['barra'], true),
('Leg press', 'Pernas na máquina', 'quadríceps', 'facil', 'academia', '4', '12-15', '90', ARRAY['Costas e quadril colados no encosto','Pés na plataforma, largura dos ombros','Desça até joelhos formarem 90°','Empurre pelos calcanhares'], 'Não trave os joelhos.', ARRAY['leg press'], true),
('Leg press unilateral', 'Corrige desequilíbrios', 'quadríceps', 'medio', 'academia', '3', '10-12 cada', '90', ARRAY['Uma perna de cada vez','Desça controladamente','Empurre pelo calcanhar'], 'Corrige desequilíbrios.', ARRAY['leg press'], true),
('Hack machine', 'Foco no quadríceps', 'quadríceps', 'medio', 'academia', '4', '10-12', '90', ARRAY['Costas apoiadas na máquina','Pés na plataforma','Desça até 90°','Empurre para cima'], 'Foco no quadríceps.', ARRAY['hack'], true),
('Agachamento goblet', 'Ótimo para aprender', 'quadríceps', 'facil', 'academia', '3', '12-15', '60', ARRAY['Halter ou kettlebell junto ao peito','Pés na largura dos ombros','Desça como se fosse sentar','Empurre pelos calcanhares'], 'Ótimo para aprender o movimento.', ARRAY['halteres','kettlebell'], true),
('Agachamento búlgaro academia', 'Excelente para glúteos', 'quadríceps', 'medio', 'academia', '3', '10-12 cada', '90', ARRAY['Pé de trás apoiado no banco','Desça até joelho de trás quase tocar o chão','Empurre pela perna da frente'], 'Excelente para glúteos.', ARRAY['banco','halteres'], true),
('Cadeira extensora', 'Isola o quadríceps', 'quadríceps', 'facil', 'academia', '3', '12-15', '60', ARRAY['Sentado na máquina','Estenda as pernas','Pause no topo','Desça controladamente'], 'Isola o quadríceps.', ARRAY['máquina'], true),
('Mesa flexora', 'Isola o posterior', 'posterior', 'facil', 'academia', '3', '12-15', '60', ARRAY['Deitado de bruços na máquina','Flexione as pernas','Pause no topo','Desça controladamente'], 'Isola o posterior da coxa.', ARRAY['máquina'], true),
('Stiff academia', 'Posterior e glúteos', 'posterior', 'medio', 'academia', '3', '10-12', '90', ARRAY['Barra na frente das coxas','Joelhos levemente flexionados','Desça empurrando o quadril para trás','Sinta o alongamento no posterior'], 'Costas sempre retas.', ARRAY['barra','halteres'], true),
('Afundo com halteres', 'Quadríceps e glúteos', 'quadríceps', 'facil', 'academia', '3', '10-12 cada', '60', ARRAY['Halteres ao lado do corpo','Dê um passo à frente','Desça até joelho de trás quase tocar o chão','Empurre para voltar'], 'Mantenha o tronco ereto.', ARRAY['halteres'], true),
('Panturrilha em pé', 'Panturrilha completa', 'panturrilha', 'facil', 'academia', '4', '15-20', '45', ARRAY['Ombros sob os apoios','Suba na ponta dos pés','Pause no topo','Desça alongando bem'], 'Amplitude completa é essencial.', ARRAY['máquina'], true),
('Panturrilha sentado', 'Trabalha o sóleo', 'panturrilha', 'facil', 'academia', '4', '15-20', '45', ARRAY['Sentado na máquina','Joelhos sob os apoios','Suba na ponta dos pés','Desça alongando bem'], 'Trabalha o sóleo.', ARRAY['máquina'], true),
('Agachamento hack', 'Foco total no quadríceps', 'quadríceps', 'dificil', 'academia', '4', '8-10', '120', ARRAY['Costas na máquina','Pés baixos na plataforma','Desça profundo','Empurre explosivamente'], 'Foco total no quadríceps.', ARRAY['hack'], true),
('Agachamento frontal', 'Mais foco no quadríceps', 'quadríceps', 'dificil', 'academia', '4', '8-10', '120', ARRAY['Barra na frente dos ombros','Cotovelos altos','Desça mantendo tronco ereto','Empurre pelos calcanhares'], 'Mais foco no quadríceps.', ARRAY['barra'], true),
('Passada com barra', 'Excelente para resistência', 'quadríceps', 'dificil', 'academia', '3', '10-12 cada', '90', ARRAY['Barra nas costas','Dê passos alternados','Desça até joelho quase tocar o chão','Continue caminhando'], 'Excelente para resistência.', ARRAY['barra'], true);

-- 🏋️ ACADEMIA - OMBRO + ABDÔMEN (15)
INSERT INTO exercises_library (name, description, muscle_group, difficulty, location, sets, reps, rest_time, instructions, tips, equipment_needed, is_active) VALUES
('Desenvolvimento máquina', 'Ombros na máquina', 'ombros', 'facil', 'academia', '3', '12-15', '60', ARRAY['Sentado na máquina, costas apoiadas','Pegadores na altura dos ombros','Empurre para cima','Desça controladamente'], 'Não trave os cotovelos.', ARRAY['máquina'], true),
('Desenvolvimento com halteres', 'Maior amplitude', 'ombros', 'medio', 'academia', '4', '10-12', '90', ARRAY['Sentado no banco, halteres na altura dos ombros','Empurre para cima','Aproxime os halteres no topo','Desça controladamente'], 'Maior amplitude que barra.', ARRAY['halteres','banco'], true),
('Desenvolvimento com barra', 'Exercício clássico', 'ombros', 'dificil', 'academia', '4', '8-10', '90', ARRAY['Barra na frente do peito','Empurre para cima','Desça até altura do queixo'], 'Exercício clássico de ombros.', ARRAY['barra','banco'], true),
('Elevação lateral academia', 'Ombros laterais', 'ombros', 'facil', 'academia', '3', '12-15', '60', ARRAY['Halteres ao lado do corpo','Levante até altura dos ombros','Cotovelos levemente flexionados','Desça controladamente'], 'Não balance o corpo.', ARRAY['halteres'], true),
('Elevação lateral na polia', 'Tensão constante', 'ombros', 'medio', 'academia', '3', '12-15', '60', ARRAY['Polia baixa, pegada cruzada','Levante até altura do ombro','Desça controladamente'], 'Tensão constante.', ARRAY['polia'], true),
('Elevação frontal', 'Ombros frontais', 'ombros', 'facil', 'academia', '3', '12-15', '60', ARRAY['Halteres na frente das coxas','Levante à frente até altura dos ombros','Desça controladamente'], 'Alterne os braços se preferir.', ARRAY['halteres'], true),
('Elevação posterior', 'Ombro posterior', 'ombros', 'facil', 'academia', '3', '12-15', '60', ARRAY['Incline o tronco para frente','Braços pendurados','Levante para os lados','Foco no ombro posterior'], 'Movimento controlado.', ARRAY['halteres'], true),
('Crucifixo invertido máquina', 'Isola ombro posterior', 'ombros', 'medio', 'academia', '3', '12-15', '60', ARRAY['Sentado de frente para a máquina','Abra os braços para trás','Aperte as escápulas','Retorne controladamente'], 'Isola o ombro posterior.', ARRAY['máquina'], true),
('Arnold press', 'Criado por Arnold', 'ombros', 'dificil', 'academia', '3', '8-10', '90', ARRAY['Halteres na frente do rosto, palmas para você','Gire e empurre para cima','Palmas para frente no topo','Desça girando de volta'], 'Criado por Arnold Schwarzenegger.', ARRAY['halteres','banco'], true),
('Remada alta', 'Ombros e trapézio', 'ombros', 'medio', 'academia', '3', '10-12', '60', ARRAY['Barra na frente das coxas','Puxe até altura do queixo','Cotovelos acima dos ombros','Desça controladamente'], 'Cuidado com os ombros.', ARRAY['barra'], true),
('Abdominal na máquina', 'Abdômen na máquina', 'abdômen', 'facil', 'academia', '3', '15-20', '45', ARRAY['Sentado na máquina','Segure os pegadores','Flexione o tronco','Retorne controladamente'], 'Foco na contração.', ARRAY['máquina'], true),
('Abdominal no cabo', 'Carga progressiva', 'abdômen', 'medio', 'academia', '3', '12-15', '60', ARRAY['Ajoelhado de frente para polia alta','Segure a corda atrás da cabeça','Flexione o tronco','Retorne controladamente'], 'Excelente para carga progressiva.', ARRAY['polia'], true),
('Prancha academia', 'Base de core', 'abdômen', 'facil', 'academia', '3', '30-60 seg', '45', ARRAY['Apoie antebraços e pontas dos pés','Corpo reto como uma tábua','Abdômen contraído','Não deixe o quadril subir ou descer'], 'Base de todo treino de core.', ARRAY[]::text[], true),
('Elevação pernas suspenso academia', 'Abdômen inferior', 'abdômen', 'dificil', 'academia', '3', '8-12', '60', ARRAY['Pendure na barra','Levante as pernas até 90 graus','Desça controladamente'], 'Não balance o corpo.', ARRAY['barra fixa'], true),
('Rotação russa com anilha', 'Oblíquos com peso', 'oblíquos', 'medio', 'academia', '3', '20 total', '60', ARRAY['Sente com joelhos dobrados','Segure anilha com as duas mãos','Gire o tronco de um lado para outro','Toque o chão com a anilha'], 'Pés podem ficar elevados.', ARRAY['anilha'], true);

-- 🏋️ ACADEMIA - GLÚTEOS + POSTERIOR (15)
INSERT INTO exercises_library (name, description, muscle_group, difficulty, location, sets, reps, rest_time, instructions, tips, equipment_needed, is_active) VALUES
('Hip thrust com barra', 'Melhor para glúteos', 'glúteos', 'medio', 'academia', '4', '10-12', '90', ARRAY['Costas apoiadas no banco','Barra sobre o quadril','Empurre o quadril para cima','Aperte os glúteos no topo'], 'Melhor exercício para glúteos.', ARRAY['barra','banco'], true),
('Elevação pélvica academia', 'Base para glúteos', 'glúteos', 'facil', 'academia', '3', '15-20', '60', ARRAY['Deite com joelhos dobrados','Pés no chão, braços ao lado','Levante o quadril contraindo glúteos','Segure 2 segundos no topo'], 'Base de todo treino de glúteos.', ARRAY[]::text[], true),
('Stiff glúteos', 'Posterior e glúteos', 'posterior', 'medio', 'academia', '3', '10-12', '90', ARRAY['Barra na frente das coxas','Joelhos levemente flexionados','Desça empurrando o quadril para trás','Sinta o alongamento no posterior'], 'Costas sempre retas.', ARRAY['barra'], true),
('Levantamento terra romeno academia', 'Posterior completo', 'posterior', 'dificil', 'academia', '4', '8-10', '120', ARRAY['Barra na frente das coxas','Joelhos levemente flexionados','Desça empurrando o quadril para trás','Suba apertando os glúteos'], 'Costas sempre retas.', ARRAY['barra'], true),
('Bom dia', 'Posterior e lombar', 'posterior', 'dificil', 'academia', '3', '10-12', '90', ARRAY['Barra nas costas','Incline o tronco para frente','Joelhos levemente flexionados','Suba apertando os glúteos'], 'Movimento controlado.', ARRAY['barra'], true),
('Cadeira abdutora', 'Glúteo médio', 'glúteos', 'facil', 'academia', '3', '15-20', '60', ARRAY['Sentado na máquina','Abra as pernas contra a resistência','Pause no final','Retorne controladamente'], 'Trabalha o glúteo médio.', ARRAY['máquina'], true),
('Cadeira adutora', 'Parte interna da coxa', 'adutores', 'facil', 'academia', '3', '15-20', '60', ARRAY['Sentado na máquina','Feche as pernas contra a resistência','Pause no final','Retorne controladamente'], 'Trabalha a parte interna da coxa.', ARRAY['máquina'], true),
('Glúteo na polia', 'Tensão constante', 'glúteos', 'facil', 'academia', '3', '12-15 cada', '60', ARRAY['Caneleira presa na polia baixa','Empurre a perna para trás','Contraia o glúteo no topo','Retorne controladamente'], 'Tensão constante.', ARRAY['polia'], true),
('Glúteo máquina', 'Isola o glúteo', 'glúteos', 'medio', 'academia', '3', '12-15 cada', '60', ARRAY['Apoiado na máquina','Empurre a plataforma para trás','Contraia o glúteo no topo','Retorne controladamente'], 'Isola o glúteo.', ARRAY['máquina'], true),
('Coice na polia', 'Foco na contração', 'glúteos', 'dificil', 'academia', '3', '12-15 cada', '60', ARRAY['Caneleira na polia baixa','Empurre a perna para trás e para cima','Contraia o glúteo no topo','Retorne controladamente'], 'Foco na contração.', ARRAY['polia'], true),
('Abdução na polia', 'Glúteo médio', 'glúteos', 'medio', 'academia', '3', '12-15 cada', '60', ARRAY['Caneleira na polia baixa','Abra a perna para o lado','Mantenha o corpo reto','Retorne controladamente'], 'Tensão constante.', ARRAY['polia'], true),
('Mesa flexora academia', 'Isola posterior', 'posterior', 'facil', 'academia', '3', '12-15', '60', ARRAY['Deitado de bruços na máquina','Flexione as pernas','Pause no topo','Desça controladamente'], 'Isola o posterior da coxa.', ARRAY['máquina'], true),
('Flexora em pé', 'Corrige desequilíbrios', 'posterior', 'medio', 'academia', '3', '12-15 cada', '60', ARRAY['Em pé na máquina','Flexione uma perna de cada vez','Pause no topo','Desça controladamente'], 'Corrige desequilíbrios.', ARRAY['máquina'], true),
('Levantamento terra sumo', 'Glúteos e adutores', 'glúteos', 'dificil', 'academia', '4', '5-8', '180', ARRAY['Pés bem abertos, pontas para fora','Pegada entre as pernas','Levante mantendo costas retas','Aperte os glúteos no topo'], 'Foco nos glúteos e adutores.', ARRAY['barra'], true),
('Afundo búlgaro academia', 'Excelente para glúteos', 'glúteos', 'medio', 'academia', '3', '10-12 cada', '90', ARRAY['Pé de trás apoiado no banco','Desça até joelho de trás quase tocar o chão','Empurre pela perna da frente'], 'Excelente para glúteos.', ARRAY['banco','halteres'], true);
